/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.api;

import uk.ac.hdruk.safepeopleregistryapi.ApiCallback;
import uk.ac.hdruk.safepeopleregistryapi.ApiClient;
import uk.ac.hdruk.safepeopleregistryapi.ApiException;
import uk.ac.hdruk.safepeopleregistryapi.ApiResponse;
import uk.ac.hdruk.safepeopleregistryapi.Configuration;
import uk.ac.hdruk.safepeopleregistryapi.Pair;
import uk.ac.hdruk.safepeopleregistryapi.ProgressRequestBody;
import uk.ac.hdruk.safepeopleregistryapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.safepeopleregistryapi.model.AccreditationIndexByRegistryId400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.Affiliation;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsGetOrganisationAffiliation200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsGetOrganisationAffiliation404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsIndexByRegistryId200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsIndexByRegistryId404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsStoreByRegistryId200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsStoreByRegistryId500Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AffiliationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AffiliationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AffiliationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for affiliationsGetOrganisationAffiliation
     * @param registryId Registry ID (required)
     * @param organisationId Organisation ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Affiliation not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsGetOrganisationAffiliationCall(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Integer organisationId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/affiliations/{registryId}/organisation/{organisationId}"
            .replace("{" + "registryId" + "}", localVarApiClient.escapeString(registryId.toString()))
            .replace("{" + "organisationId" + "}", localVarApiClient.escapeString(organisationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call affiliationsGetOrganisationAffiliationValidateBeforeCall(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Integer organisationId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'registryId' is set
        if (registryId == null) {
            throw new ApiException("Missing the required parameter 'registryId' when calling affiliationsGetOrganisationAffiliation(Async)");
        }

        // verify the required parameter 'organisationId' is set
        if (organisationId == null) {
            throw new ApiException("Missing the required parameter 'organisationId' when calling affiliationsGetOrganisationAffiliation(Async)");
        }

        return affiliationsGetOrganisationAffiliationCall(registryId, organisationId, _callback);

    }

    /**
     * Return a specific organisation&#39;s affiliation by registry ID and organisation ID
     * Get a specific organisation&#39;s affiliation for a given registry
     * @param registryId Registry ID (required)
     * @param organisationId Organisation ID (required)
     * @return AffiliationsGetOrganisationAffiliation200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Affiliation not found </td><td>  -  </td></tr>
     </table>
     */
    public AffiliationsGetOrganisationAffiliation200Response affiliationsGetOrganisationAffiliation(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Integer organisationId) throws ApiException {
        ApiResponse<AffiliationsGetOrganisationAffiliation200Response> localVarResp = affiliationsGetOrganisationAffiliationWithHttpInfo(registryId, organisationId);
        return localVarResp.getData();
    }

    /**
     * Return a specific organisation&#39;s affiliation by registry ID and organisation ID
     * Get a specific organisation&#39;s affiliation for a given registry
     * @param registryId Registry ID (required)
     * @param organisationId Organisation ID (required)
     * @return ApiResponse&lt;AffiliationsGetOrganisationAffiliation200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Affiliation not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AffiliationsGetOrganisationAffiliation200Response> affiliationsGetOrganisationAffiliationWithHttpInfo(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Integer organisationId) throws ApiException {
        okhttp3.Call localVarCall = affiliationsGetOrganisationAffiliationValidateBeforeCall(registryId, organisationId, null);
        Type localVarReturnType = new TypeToken<AffiliationsGetOrganisationAffiliation200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return a specific organisation&#39;s affiliation by registry ID and organisation ID (asynchronously)
     * Get a specific organisation&#39;s affiliation for a given registry
     * @param registryId Registry ID (required)
     * @param organisationId Organisation ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Affiliation not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsGetOrganisationAffiliationAsync(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Integer organisationId, final ApiCallback<AffiliationsGetOrganisationAffiliation200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = affiliationsGetOrganisationAffiliationValidateBeforeCall(registryId, organisationId, _callback);
        Type localVarReturnType = new TypeToken<AffiliationsGetOrganisationAffiliation200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for affiliationsIndexByRegistryId
     * @param registryId Affiliations registry id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsIndexByRegistryIdCall(@javax.annotation.Nonnull Integer registryId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/affiliations/{registryId}"
            .replace("{" + "registryId" + "}", localVarApiClient.escapeString(registryId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call affiliationsIndexByRegistryIdValidateBeforeCall(@javax.annotation.Nonnull Integer registryId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'registryId' is set
        if (registryId == null) {
            throw new ApiException("Missing the required parameter 'registryId' when calling affiliationsIndexByRegistryId(Async)");
        }

        return affiliationsIndexByRegistryIdCall(registryId, _callback);

    }

    /**
     * Affiliations@show
     * Return a list of affiliations by registry id
     * @param registryId Affiliations registry id (required)
     * @return AffiliationsIndexByRegistryId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public AffiliationsIndexByRegistryId200Response affiliationsIndexByRegistryId(@javax.annotation.Nonnull Integer registryId) throws ApiException {
        ApiResponse<AffiliationsIndexByRegistryId200Response> localVarResp = affiliationsIndexByRegistryIdWithHttpInfo(registryId);
        return localVarResp.getData();
    }

    /**
     * Affiliations@show
     * Return a list of affiliations by registry id
     * @param registryId Affiliations registry id (required)
     * @return ApiResponse&lt;AffiliationsIndexByRegistryId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AffiliationsIndexByRegistryId200Response> affiliationsIndexByRegistryIdWithHttpInfo(@javax.annotation.Nonnull Integer registryId) throws ApiException {
        okhttp3.Call localVarCall = affiliationsIndexByRegistryIdValidateBeforeCall(registryId, null);
        Type localVarReturnType = new TypeToken<AffiliationsIndexByRegistryId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Affiliations@show (asynchronously)
     * Return a list of affiliations by registry id
     * @param registryId Affiliations registry id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsIndexByRegistryIdAsync(@javax.annotation.Nonnull Integer registryId, final ApiCallback<AffiliationsIndexByRegistryId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = affiliationsIndexByRegistryIdValidateBeforeCall(registryId, _callback);
        Type localVarReturnType = new TypeToken<AffiliationsIndexByRegistryId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for affiliationsStoreByRegistryId
     * @param registryId Registry entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsStoreByRegistryIdCall(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Affiliation affiliation, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = affiliation;

        // create path and map variables
        String localVarPath = "/api/v1/affiliations/{registryId}"
            .replace("{" + "registryId" + "}", localVarApiClient.escapeString(registryId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call affiliationsStoreByRegistryIdValidateBeforeCall(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Affiliation affiliation, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'registryId' is set
        if (registryId == null) {
            throw new ApiException("Missing the required parameter 'registryId' when calling affiliationsStoreByRegistryId(Async)");
        }

        // verify the required parameter 'affiliation' is set
        if (affiliation == null) {
            throw new ApiException("Missing the required parameter 'affiliation' when calling affiliationsStoreByRegistryId(Async)");
        }

        return affiliationsStoreByRegistryIdCall(registryId, affiliation, _callback);

    }

    /**
     * Affiliations@store
     * Create an Affiliation entry
     * @param registryId Registry entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @return AffiliationsStoreByRegistryId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public AffiliationsStoreByRegistryId200Response affiliationsStoreByRegistryId(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Affiliation affiliation) throws ApiException {
        ApiResponse<AffiliationsStoreByRegistryId200Response> localVarResp = affiliationsStoreByRegistryIdWithHttpInfo(registryId, affiliation);
        return localVarResp.getData();
    }

    /**
     * Affiliations@store
     * Create an Affiliation entry
     * @param registryId Registry entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @return ApiResponse&lt;AffiliationsStoreByRegistryId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AffiliationsStoreByRegistryId200Response> affiliationsStoreByRegistryIdWithHttpInfo(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Affiliation affiliation) throws ApiException {
        okhttp3.Call localVarCall = affiliationsStoreByRegistryIdValidateBeforeCall(registryId, affiliation, null);
        Type localVarReturnType = new TypeToken<AffiliationsStoreByRegistryId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Affiliations@store (asynchronously)
     * Create an Affiliation entry
     * @param registryId Registry entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsStoreByRegistryIdAsync(@javax.annotation.Nonnull Integer registryId, @javax.annotation.Nonnull Affiliation affiliation, final ApiCallback<AffiliationsStoreByRegistryId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = affiliationsStoreByRegistryIdValidateBeforeCall(registryId, affiliation, _callback);
        Type localVarReturnType = new TypeToken<AffiliationsStoreByRegistryId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for affiliationsUpdate
     * @param id Affiliation entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsUpdateCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Affiliation affiliation, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = affiliation;

        // create path and map variables
        String localVarPath = "/api/v1/affiliations/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call affiliationsUpdateValidateBeforeCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Affiliation affiliation, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling affiliationsUpdate(Async)");
        }

        // verify the required parameter 'affiliation' is set
        if (affiliation == null) {
            throw new ApiException("Missing the required parameter 'affiliation' when calling affiliationsUpdate(Async)");
        }

        return affiliationsUpdateCall(id, affiliation, _callback);

    }

    /**
     * Affiliations@update
     * Update an Affiliation entry
     * @param id Affiliation entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @return AffiliationsStoreByRegistryId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public AffiliationsStoreByRegistryId200Response affiliationsUpdate(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Affiliation affiliation) throws ApiException {
        ApiResponse<AffiliationsStoreByRegistryId200Response> localVarResp = affiliationsUpdateWithHttpInfo(id, affiliation);
        return localVarResp.getData();
    }

    /**
     * Affiliations@update
     * Update an Affiliation entry
     * @param id Affiliation entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @return ApiResponse&lt;AffiliationsStoreByRegistryId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AffiliationsStoreByRegistryId200Response> affiliationsUpdateWithHttpInfo(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Affiliation affiliation) throws ApiException {
        okhttp3.Call localVarCall = affiliationsUpdateValidateBeforeCall(id, affiliation, null);
        Type localVarReturnType = new TypeToken<AffiliationsStoreByRegistryId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Affiliations@update (asynchronously)
     * Update an Affiliation entry
     * @param id Affiliation entry ID (required)
     * @param affiliation Affiliation definition (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsUpdateAsync(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull Affiliation affiliation, final ApiCallback<AffiliationsStoreByRegistryId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = affiliationsUpdateValidateBeforeCall(id, affiliation, _callback);
        Type localVarReturnType = new TypeToken<AffiliationsStoreByRegistryId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for affiliationsVerifyEmail
     * @param verificationCode Email verification code (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsVerifyEmailCall(@javax.annotation.Nonnull String verificationCode, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/affiliations/verify_email/{verificationCode}"
            .replace("{" + "verificationCode" + "}", localVarApiClient.escapeString(verificationCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call affiliationsVerifyEmailValidateBeforeCall(@javax.annotation.Nonnull String verificationCode, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'verificationCode' is set
        if (verificationCode == null) {
            throw new ApiException("Missing the required parameter 'verificationCode' when calling affiliationsVerifyEmail(Async)");
        }

        return affiliationsVerifyEmailCall(verificationCode, _callback);

    }

    /**
     * Affiliations@verifyEmail
     * Update an Affiliation entry with verification
     * @param verificationCode Email verification code (required)
     * @return AffiliationsStoreByRegistryId200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public AffiliationsStoreByRegistryId200Response affiliationsVerifyEmail(@javax.annotation.Nonnull String verificationCode) throws ApiException {
        ApiResponse<AffiliationsStoreByRegistryId200Response> localVarResp = affiliationsVerifyEmailWithHttpInfo(verificationCode);
        return localVarResp.getData();
    }

    /**
     * Affiliations@verifyEmail
     * Update an Affiliation entry with verification
     * @param verificationCode Email verification code (required)
     * @return ApiResponse&lt;AffiliationsStoreByRegistryId200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AffiliationsStoreByRegistryId200Response> affiliationsVerifyEmailWithHttpInfo(@javax.annotation.Nonnull String verificationCode) throws ApiException {
        okhttp3.Call localVarCall = affiliationsVerifyEmailValidateBeforeCall(verificationCode, null);
        Type localVarReturnType = new TypeToken<AffiliationsStoreByRegistryId200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Affiliations@verifyEmail (asynchronously)
     * Update an Affiliation entry with verification
     * @param verificationCode Email verification code (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call affiliationsVerifyEmailAsync(@javax.annotation.Nonnull String verificationCode, final ApiCallback<AffiliationsStoreByRegistryId200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = affiliationsVerifyEmailValidateBeforeCall(verificationCode, _callback);
        Type localVarReturnType = new TypeToken<AffiliationsStoreByRegistryId200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
