/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.api;

import uk.ac.hdruk.safepeopleregistryapi.ApiCallback;
import uk.ac.hdruk.safepeopleregistryapi.ApiClient;
import uk.ac.hdruk.safepeopleregistryapi.ApiException;
import uk.ac.hdruk.safepeopleregistryapi.ApiResponse;
import uk.ac.hdruk.safepeopleregistryapi.Configuration;
import uk.ac.hdruk.safepeopleregistryapi.Pair;
import uk.ac.hdruk.safepeopleregistryapi.ProgressRequestBody;
import uk.ac.hdruk.safepeopleregistryapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.safepeopleregistryapi.model.AccreditationIndexByRegistryId400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansCreateCustodianValidationChecks400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansCreateCustodianValidationChecksRequest;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansGetCustodianUsers200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansGetCustodianUsers404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansGetOrganisationUsers200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansGetOrganisationUsers404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansGetRules200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodiansGetRules404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationCheck;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CustodiansApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CustodiansApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CustodiansApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for custodiansCreateCustodianValidationChecks
     * @param custodianId ID of the custodian (required)
     * @param custodiansCreateCustodianValidationChecksRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created and assigned successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansCreateCustodianValidationChecksCall(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull CustodiansCreateCustodianValidationChecksRequest custodiansCreateCustodianValidationChecksRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = custodiansCreateCustodianValidationChecksRequest;

        // create path and map variables
        String localVarPath = "/api/v1/custodians/{custodianId}/validation_checks"
            .replace("{" + "custodianId" + "}", localVarApiClient.escapeString(custodianId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call custodiansCreateCustodianValidationChecksValidateBeforeCall(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull CustodiansCreateCustodianValidationChecksRequest custodiansCreateCustodianValidationChecksRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'custodianId' is set
        if (custodianId == null) {
            throw new ApiException("Missing the required parameter 'custodianId' when calling custodiansCreateCustodianValidationChecks(Async)");
        }

        // verify the required parameter 'custodiansCreateCustodianValidationChecksRequest' is set
        if (custodiansCreateCustodianValidationChecksRequest == null) {
            throw new ApiException("Missing the required parameter 'custodiansCreateCustodianValidationChecksRequest' when calling custodiansCreateCustodianValidationChecks(Async)");
        }

        return custodiansCreateCustodianValidationChecksCall(custodianId, custodiansCreateCustodianValidationChecksRequest, _callback);

    }

    /**
     * Assign a validation check to a custodian
     * Creates a new validation check and assigns it to a specific custodian via the custodian_has_validation_check pivot table.
     * @param custodianId ID of the custodian (required)
     * @param custodiansCreateCustodianValidationChecksRequest  (required)
     * @return ValidationCheck
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created and assigned successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public ValidationCheck custodiansCreateCustodianValidationChecks(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull CustodiansCreateCustodianValidationChecksRequest custodiansCreateCustodianValidationChecksRequest) throws ApiException {
        ApiResponse<ValidationCheck> localVarResp = custodiansCreateCustodianValidationChecksWithHttpInfo(custodianId, custodiansCreateCustodianValidationChecksRequest);
        return localVarResp.getData();
    }

    /**
     * Assign a validation check to a custodian
     * Creates a new validation check and assigns it to a specific custodian via the custodian_has_validation_check pivot table.
     * @param custodianId ID of the custodian (required)
     * @param custodiansCreateCustodianValidationChecksRequest  (required)
     * @return ApiResponse&lt;ValidationCheck&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created and assigned successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ValidationCheck> custodiansCreateCustodianValidationChecksWithHttpInfo(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull CustodiansCreateCustodianValidationChecksRequest custodiansCreateCustodianValidationChecksRequest) throws ApiException {
        okhttp3.Call localVarCall = custodiansCreateCustodianValidationChecksValidateBeforeCall(custodianId, custodiansCreateCustodianValidationChecksRequest, null);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Assign a validation check to a custodian (asynchronously)
     * Creates a new validation check and assigns it to a specific custodian via the custodian_has_validation_check pivot table.
     * @param custodianId ID of the custodian (required)
     * @param custodiansCreateCustodianValidationChecksRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created and assigned successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansCreateCustodianValidationChecksAsync(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull CustodiansCreateCustodianValidationChecksRequest custodiansCreateCustodianValidationChecksRequest, final ApiCallback<ValidationCheck> _callback) throws ApiException {

        okhttp3.Call localVarCall = custodiansCreateCustodianValidationChecksValidateBeforeCall(custodianId, custodiansCreateCustodianValidationChecksRequest, _callback);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for custodiansGetCustodianUsers
     * @param custodianId ID of the custodian (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved custodian users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian users not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetCustodianUsersCall(@javax.annotation.Nonnull Integer custodianId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/custodians/{custodianId}/custodian_users"
            .replace("{" + "custodianId" + "}", localVarApiClient.escapeString(custodianId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call custodiansGetCustodianUsersValidateBeforeCall(@javax.annotation.Nonnull Integer custodianId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'custodianId' is set
        if (custodianId == null) {
            throw new ApiException("Missing the required parameter 'custodianId' when calling custodiansGetCustodianUsers(Async)");
        }

        return custodiansGetCustodianUsersCall(custodianId, _callback);

    }

    /**
     * Get list of people for a custodian
     * Fetches the list of custodian users based on the custodian id.
     * @param custodianId ID of the custodian (required)
     * @return CustodiansGetCustodianUsers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved custodian users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian users not found </td><td>  -  </td></tr>
     </table>
     */
    public CustodiansGetCustodianUsers200Response custodiansGetCustodianUsers(@javax.annotation.Nonnull Integer custodianId) throws ApiException {
        ApiResponse<CustodiansGetCustodianUsers200Response> localVarResp = custodiansGetCustodianUsersWithHttpInfo(custodianId);
        return localVarResp.getData();
    }

    /**
     * Get list of people for a custodian
     * Fetches the list of custodian users based on the custodian id.
     * @param custodianId ID of the custodian (required)
     * @return ApiResponse&lt;CustodiansGetCustodianUsers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved custodian users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian users not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CustodiansGetCustodianUsers200Response> custodiansGetCustodianUsersWithHttpInfo(@javax.annotation.Nonnull Integer custodianId) throws ApiException {
        okhttp3.Call localVarCall = custodiansGetCustodianUsersValidateBeforeCall(custodianId, null);
        Type localVarReturnType = new TypeToken<CustodiansGetCustodianUsers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get list of people for a custodian (asynchronously)
     * Fetches the list of custodian users based on the custodian id.
     * @param custodianId ID of the custodian (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved custodian users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian users not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetCustodianUsersAsync(@javax.annotation.Nonnull Integer custodianId, final ApiCallback<CustodiansGetCustodianUsers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = custodiansGetCustodianUsersValidateBeforeCall(custodianId, _callback);
        Type localVarReturnType = new TypeToken<CustodiansGetCustodianUsers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for custodiansGetCustodianValidationChecks
     * @param custodianId ID of the custodian (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetCustodianValidationChecksCall(@javax.annotation.Nonnull Integer custodianId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/custodians/{custodianId}/validation_checks"
            .replace("{" + "custodianId" + "}", localVarApiClient.escapeString(custodianId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call custodiansGetCustodianValidationChecksValidateBeforeCall(@javax.annotation.Nonnull Integer custodianId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'custodianId' is set
        if (custodianId == null) {
            throw new ApiException("Missing the required parameter 'custodianId' when calling custodiansGetCustodianValidationChecks(Async)");
        }

        return custodiansGetCustodianValidationChecksCall(custodianId, _callback);

    }

    /**
     * Get validation checks assigned to a custodian
     * Returns the list of validation checks associated with a specific custodian.
     * @param custodianId ID of the custodian (required)
     * @return List&lt;ValidationCheck&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public List<ValidationCheck> custodiansGetCustodianValidationChecks(@javax.annotation.Nonnull Integer custodianId) throws ApiException {
        ApiResponse<List<ValidationCheck>> localVarResp = custodiansGetCustodianValidationChecksWithHttpInfo(custodianId);
        return localVarResp.getData();
    }

    /**
     * Get validation checks assigned to a custodian
     * Returns the list of validation checks associated with a specific custodian.
     * @param custodianId ID of the custodian (required)
     * @return ApiResponse&lt;List&lt;ValidationCheck&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ValidationCheck>> custodiansGetCustodianValidationChecksWithHttpInfo(@javax.annotation.Nonnull Integer custodianId) throws ApiException {
        okhttp3.Call localVarCall = custodiansGetCustodianValidationChecksValidateBeforeCall(custodianId, null);
        Type localVarReturnType = new TypeToken<List<ValidationCheck>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get validation checks assigned to a custodian (asynchronously)
     * Returns the list of validation checks associated with a specific custodian.
     * @param custodianId ID of the custodian (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetCustodianValidationChecksAsync(@javax.annotation.Nonnull Integer custodianId, final ApiCallback<List<ValidationCheck>> _callback) throws ApiException {

        okhttp3.Call localVarCall = custodiansGetCustodianValidationChecksValidateBeforeCall(custodianId, _callback);
        Type localVarReturnType = new TypeToken<List<ValidationCheck>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for custodiansGetOrganisationUsers
     * @param custodianId ID of the custodian (required)
     * @param organisationId ID of the organisation (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetOrganisationUsersCall(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer organisationId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/custodians/{custodianId}/organisations/{organisationId}/users"
            .replace("{" + "custodianId" + "}", localVarApiClient.escapeString(custodianId.toString()))
            .replace("{" + "organisationId" + "}", localVarApiClient.escapeString(organisationId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call custodiansGetOrganisationUsersValidateBeforeCall(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer organisationId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'custodianId' is set
        if (custodianId == null) {
            throw new ApiException("Missing the required parameter 'custodianId' when calling custodiansGetOrganisationUsers(Async)");
        }

        // verify the required parameter 'organisationId' is set
        if (organisationId == null) {
            throw new ApiException("Missing the required parameter 'organisationId' when calling custodiansGetOrganisationUsers(Async)");
        }

        return custodiansGetOrganisationUsersCall(custodianId, organisationId, _callback);

    }

    /**
     * Get list of people for organisation
     * Fetches the list of users associated with the given custodian and organisations IDs.
     * @param custodianId ID of the custodian (required)
     * @param organisationId ID of the organisation (required)
     * @return CustodiansGetOrganisationUsers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public CustodiansGetOrganisationUsers200Response custodiansGetOrganisationUsers(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer organisationId) throws ApiException {
        ApiResponse<CustodiansGetOrganisationUsers200Response> localVarResp = custodiansGetOrganisationUsersWithHttpInfo(custodianId, organisationId);
        return localVarResp.getData();
    }

    /**
     * Get list of people for organisation
     * Fetches the list of users associated with the given custodian and organisations IDs.
     * @param custodianId ID of the custodian (required)
     * @param organisationId ID of the organisation (required)
     * @return ApiResponse&lt;CustodiansGetOrganisationUsers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CustodiansGetOrganisationUsers200Response> custodiansGetOrganisationUsersWithHttpInfo(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer organisationId) throws ApiException {
        okhttp3.Call localVarCall = custodiansGetOrganisationUsersValidateBeforeCall(custodianId, organisationId, null);
        Type localVarReturnType = new TypeToken<CustodiansGetOrganisationUsers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get list of people for organisation (asynchronously)
     * Fetches the list of users associated with the given custodian and organisations IDs.
     * @param custodianId ID of the custodian (required)
     * @param organisationId ID of the organisation (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetOrganisationUsersAsync(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer organisationId, final ApiCallback<CustodiansGetOrganisationUsers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = custodiansGetOrganisationUsersValidateBeforeCall(custodianId, organisationId, _callback);
        Type localVarReturnType = new TypeToken<CustodiansGetOrganisationUsers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for custodiansGetRules
     * @param id ID of the custodian (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved rules </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetRulesCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/custodians/{id}/rules"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call custodiansGetRulesValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling custodiansGetRules(Async)");
        }

        return custodiansGetRulesCall(id, _callback);

    }

    /**
     * Get rules for a specific custodian
     * Fetches the list of rules associated with the given custodian ID.
     * @param id ID of the custodian (required)
     * @return CustodiansGetRules200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved rules </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public CustodiansGetRules200Response custodiansGetRules(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<CustodiansGetRules200Response> localVarResp = custodiansGetRulesWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get rules for a specific custodian
     * Fetches the list of rules associated with the given custodian ID.
     * @param id ID of the custodian (required)
     * @return ApiResponse&lt;CustodiansGetRules200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved rules </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CustodiansGetRules200Response> custodiansGetRulesWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = custodiansGetRulesValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<CustodiansGetRules200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get rules for a specific custodian (asynchronously)
     * Fetches the list of rules associated with the given custodian ID.
     * @param id ID of the custodian (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved rules </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Custodian not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetRulesAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<CustodiansGetRules200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = custodiansGetRulesValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<CustodiansGetRules200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for custodiansGetStatusesUsers
     * @param custodianId ID of the custodian (required)
     * @param projectUserId ID of the project user (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetStatusesUsersCall(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer projectUserId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/custodians/{custodianId}/projectUsers/{projectUserId}/statuses"
            .replace("{" + "custodianId" + "}", localVarApiClient.escapeString(custodianId.toString()))
            .replace("{" + "projectUserId" + "}", localVarApiClient.escapeString(projectUserId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call custodiansGetStatusesUsersValidateBeforeCall(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer projectUserId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'custodianId' is set
        if (custodianId == null) {
            throw new ApiException("Missing the required parameter 'custodianId' when calling custodiansGetStatusesUsers(Async)");
        }

        // verify the required parameter 'projectUserId' is set
        if (projectUserId == null) {
            throw new ApiException("Missing the required parameter 'projectUserId' when calling custodiansGetStatusesUsers(Async)");
        }

        return custodiansGetStatusesUsersCall(custodianId, projectUserId, _callback);

    }

    /**
     * Get statuses for a user in a project/organisation/custodian
     * Fetches the user statuses given custodian and organisations and project and user IDs.
     * @param custodianId ID of the custodian (required)
     * @param projectUserId ID of the project user (required)
     * @return CustodiansGetOrganisationUsers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public CustodiansGetOrganisationUsers200Response custodiansGetStatusesUsers(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer projectUserId) throws ApiException {
        ApiResponse<CustodiansGetOrganisationUsers200Response> localVarResp = custodiansGetStatusesUsersWithHttpInfo(custodianId, projectUserId);
        return localVarResp.getData();
    }

    /**
     * Get statuses for a user in a project/organisation/custodian
     * Fetches the user statuses given custodian and organisations and project and user IDs.
     * @param custodianId ID of the custodian (required)
     * @param projectUserId ID of the project user (required)
     * @return ApiResponse&lt;CustodiansGetOrganisationUsers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CustodiansGetOrganisationUsers200Response> custodiansGetStatusesUsersWithHttpInfo(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer projectUserId) throws ApiException {
        okhttp3.Call localVarCall = custodiansGetStatusesUsersValidateBeforeCall(custodianId, projectUserId, null);
        Type localVarReturnType = new TypeToken<CustodiansGetOrganisationUsers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get statuses for a user in a project/organisation/custodian (asynchronously)
     * Fetches the user statuses given custodian and organisations and project and user IDs.
     * @param custodianId ID of the custodian (required)
     * @param projectUserId ID of the project user (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully retrieved organisation users </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Organisation users not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call custodiansGetStatusesUsersAsync(@javax.annotation.Nonnull Integer custodianId, @javax.annotation.Nonnull Integer projectUserId, final ApiCallback<CustodiansGetOrganisationUsers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = custodiansGetStatusesUsersValidateBeforeCall(custodianId, projectUserId, _callback);
        Type localVarReturnType = new TypeToken<CustodiansGetOrganisationUsers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
