/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.api;

import uk.ac.hdruk.safepeopleregistryapi.ApiCallback;
import uk.ac.hdruk.safepeopleregistryapi.ApiClient;
import uk.ac.hdruk.safepeopleregistryapi.ApiException;
import uk.ac.hdruk.safepeopleregistryapi.ApiResponse;
import uk.ac.hdruk.safepeopleregistryapi.Configuration;
import uk.ac.hdruk.safepeopleregistryapi.Pair;
import uk.ac.hdruk.safepeopleregistryapi.ProgressRequestBody;
import uk.ac.hdruk.safepeopleregistryapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.safepeopleregistryapi.model.AccreditationIndexByRegistryId400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.AffiliationsIndexByRegistryId404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.OrganisationGetDelegates200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.OrganisationGetProjects200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.OrganisationGetUsers200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.OrganisationIndex200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OrganisationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public OrganisationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public OrganisationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for organisationGetDelegates
     * @param id Organisation ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetDelegatesCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/organisations/{id}/delegates"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call organisationGetDelegatesValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling organisationGetDelegates(Async)");
        }

        return organisationGetDelegatesCall(id, _callback);

    }

    /**
     * Return all delegates associated with an organisation
     * Return all delegates associated with an organisation
     * @param id Organisation ID (required)
     * @return OrganisationGetDelegates200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public OrganisationGetDelegates200Response organisationGetDelegates(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<OrganisationGetDelegates200Response> localVarResp = organisationGetDelegatesWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Return all delegates associated with an organisation
     * Return all delegates associated with an organisation
     * @param id Organisation ID (required)
     * @return ApiResponse&lt;OrganisationGetDelegates200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganisationGetDelegates200Response> organisationGetDelegatesWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = organisationGetDelegatesValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<OrganisationGetDelegates200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return all delegates associated with an organisation (asynchronously)
     * Return all delegates associated with an organisation
     * @param id Organisation ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetDelegatesAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<OrganisationGetDelegates200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = organisationGetDelegatesValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<OrganisationGetDelegates200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for organisationGetProjects
     * @param id Organisation ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetProjectsCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/organisations/{id}/projects"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call organisationGetProjectsValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling organisationGetProjects(Async)");
        }

        return organisationGetProjectsCall(id, _callback);

    }

    /**
     * organisation@getProjects
     * Return an all projects associated with an organisation (i.e. data-custodian)
     * @param id Organisation ID (required)
     * @return OrganisationGetProjects200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public OrganisationGetProjects200Response organisationGetProjects(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<OrganisationGetProjects200Response> localVarResp = organisationGetProjectsWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * organisation@getProjects
     * Return an all projects associated with an organisation (i.e. data-custodian)
     * @param id Organisation ID (required)
     * @return ApiResponse&lt;OrganisationGetProjects200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganisationGetProjects200Response> organisationGetProjectsWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = organisationGetProjectsValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<OrganisationGetProjects200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * organisation@getProjects (asynchronously)
     * Return an all projects associated with an organisation (i.e. data-custodian)
     * @param id Organisation ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetProjectsAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<OrganisationGetProjects200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = organisationGetProjectsValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<OrganisationGetProjects200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for organisationGetSponsorshipsProjects
     * @param id Organisation ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetSponsorshipsProjectsCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/organisations/{id}/projects/sponsorships"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call organisationGetSponsorshipsProjectsValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling organisationGetSponsorshipsProjects(Async)");
        }

        return organisationGetSponsorshipsProjectsCall(id, _callback);

    }

    /**
     * organisation@getSponsorshipsProjects
     * Return an all projects associated with an organisation with sponsorships (i.e. data-custodian)
     * @param id Organisation ID (required)
     * @return OrganisationGetProjects200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public OrganisationGetProjects200Response organisationGetSponsorshipsProjects(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<OrganisationGetProjects200Response> localVarResp = organisationGetSponsorshipsProjectsWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * organisation@getSponsorshipsProjects
     * Return an all projects associated with an organisation with sponsorships (i.e. data-custodian)
     * @param id Organisation ID (required)
     * @return ApiResponse&lt;OrganisationGetProjects200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganisationGetProjects200Response> organisationGetSponsorshipsProjectsWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = organisationGetSponsorshipsProjectsValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<OrganisationGetProjects200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * organisation@getSponsorshipsProjects (asynchronously)
     * Return an all projects associated with an organisation with sponsorships (i.e. data-custodian)
     * @param id Organisation ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetSponsorshipsProjectsAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<OrganisationGetProjects200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = organisationGetSponsorshipsProjectsValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<OrganisationGetProjects200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for organisationGetUsers
     * @param id Organisation ID (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetUsersCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/organisations/{id}/users"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call organisationGetUsersValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling organisationGetUsers(Async)");
        }

        return organisationGetUsersCall(id, _callback);

    }

    /**
     * organisation@getUsers
     * Return all users associated with an organisation
     * @param id Organisation ID (required)
     * @return OrganisationGetUsers200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public OrganisationGetUsers200Response organisationGetUsers(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<OrganisationGetUsers200Response> localVarResp = organisationGetUsersWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * organisation@getUsers
     * Return all users associated with an organisation
     * @param id Organisation ID (required)
     * @return ApiResponse&lt;OrganisationGetUsers200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganisationGetUsers200Response> organisationGetUsersWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = organisationGetUsersValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<OrganisationGetUsers200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * organisation@getUsers (asynchronously)
     * Return all users associated with an organisation
     * @param id Organisation ID (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationGetUsersAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<OrganisationGetUsers200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = organisationGetUsersValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<OrganisationGetUsers200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for organisationIndex
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationIndexCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/organisations";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call organisationIndexValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return organisationIndexCall(_callback);

    }

    /**
     * organisation@index
     * Return a list of organisations
     * @return OrganisationIndex200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public OrganisationIndex200Response organisationIndex() throws ApiException {
        ApiResponse<OrganisationIndex200Response> localVarResp = organisationIndexWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * organisation@index
     * Return a list of organisations
     * @return ApiResponse&lt;OrganisationIndex200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<OrganisationIndex200Response> organisationIndexWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = organisationIndexValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<OrganisationIndex200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * organisation@index (asynchronously)
     * Return a list of organisations
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call organisationIndexAsync(final ApiCallback<OrganisationIndex200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = organisationIndexValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<OrganisationIndex200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
