/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.api;

import uk.ac.hdruk.safepeopleregistryapi.ApiCallback;
import uk.ac.hdruk.safepeopleregistryapi.ApiClient;
import uk.ac.hdruk.safepeopleregistryapi.ApiException;
import uk.ac.hdruk.safepeopleregistryapi.ApiResponse;
import uk.ac.hdruk.safepeopleregistryapi.Configuration;
import uk.ac.hdruk.safepeopleregistryapi.Pair;
import uk.ac.hdruk.safepeopleregistryapi.ProgressRequestBody;
import uk.ac.hdruk.safepeopleregistryapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import uk.ac.hdruk.safepeopleregistryapi.model.AccreditationIndexByRegistryId400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationCheck;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationChecksDestroy200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationChecksShow404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationChecksStoreRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ValidationChecksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ValidationChecksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ValidationChecksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for validationChecksDestroy
     * @param id ID of the validation check (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check deleted successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksDestroyCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/validation_checks/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validationChecksDestroyValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling validationChecksDestroy(Async)");
        }

        return validationChecksDestroyCall(id, _callback);

    }

    /**
     * Delete a validation check
     * Remove a validation check.
     * @param id ID of the validation check (required)
     * @return ValidationChecksDestroy200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check deleted successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public ValidationChecksDestroy200Response validationChecksDestroy(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<ValidationChecksDestroy200Response> localVarResp = validationChecksDestroyWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Delete a validation check
     * Remove a validation check.
     * @param id ID of the validation check (required)
     * @return ApiResponse&lt;ValidationChecksDestroy200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check deleted successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ValidationChecksDestroy200Response> validationChecksDestroyWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = validationChecksDestroyValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ValidationChecksDestroy200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a validation check (asynchronously)
     * Remove a validation check.
     * @param id ID of the validation check (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check deleted successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksDestroyAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<ValidationChecksDestroy200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = validationChecksDestroyValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ValidationChecksDestroy200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for validationChecksIndex
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksIndexCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/validation_checks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validationChecksIndexValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return validationChecksIndexCall(_callback);

    }

    /**
     * List all validation checks
     * Retrieve all validation checks.
     * @return List&lt;ValidationCheck&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
     </table>
     */
    public List<ValidationCheck> validationChecksIndex() throws ApiException {
        ApiResponse<List<ValidationCheck>> localVarResp = validationChecksIndexWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List all validation checks
     * Retrieve all validation checks.
     * @return ApiResponse&lt;List&lt;ValidationCheck&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ValidationCheck>> validationChecksIndexWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = validationChecksIndexValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<ValidationCheck>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List all validation checks (asynchronously)
     * Retrieve all validation checks.
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation checks retrieved successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksIndexAsync(final ApiCallback<List<ValidationCheck>> _callback) throws ApiException {

        okhttp3.Call localVarCall = validationChecksIndexValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<ValidationCheck>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for validationChecksShow
     * @param id ID of the validation check (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksShowCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/validation_checks/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validationChecksShowValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling validationChecksShow(Async)");
        }

        return validationChecksShowCall(id, _callback);

    }

    /**
     * Get a single validation check
     * Retrieve a specific validation check by ID.
     * @param id ID of the validation check (required)
     * @return ValidationCheck
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public ValidationCheck validationChecksShow(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<ValidationCheck> localVarResp = validationChecksShowWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get a single validation check
     * Retrieve a specific validation check by ID.
     * @param id ID of the validation check (required)
     * @return ApiResponse&lt;ValidationCheck&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ValidationCheck> validationChecksShowWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = validationChecksShowValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a single validation check (asynchronously)
     * Retrieve a specific validation check by ID.
     * @param id ID of the validation check (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check retrieved successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksShowAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<ValidationCheck> _callback) throws ApiException {

        okhttp3.Call localVarCall = validationChecksShowValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for validationChecksStore
     * @param validationChecksStoreRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksStoreCall(@javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = validationChecksStoreRequest;

        // create path and map variables
        String localVarPath = "/api/v1/validation_checks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validationChecksStoreValidateBeforeCall(@javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'validationChecksStoreRequest' is set
        if (validationChecksStoreRequest == null) {
            throw new ApiException("Missing the required parameter 'validationChecksStoreRequest' when calling validationChecksStore(Async)");
        }

        return validationChecksStoreCall(validationChecksStoreRequest, _callback);

    }

    /**
     * Create a new validation check
     * Create a new validation check entry.
     * @param validationChecksStoreRequest  (required)
     * @return ValidationCheck
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created successfully </td><td>  -  </td></tr>
     </table>
     */
    public ValidationCheck validationChecksStore(@javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest) throws ApiException {
        ApiResponse<ValidationCheck> localVarResp = validationChecksStoreWithHttpInfo(validationChecksStoreRequest);
        return localVarResp.getData();
    }

    /**
     * Create a new validation check
     * Create a new validation check entry.
     * @param validationChecksStoreRequest  (required)
     * @return ApiResponse&lt;ValidationCheck&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ValidationCheck> validationChecksStoreWithHttpInfo(@javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest) throws ApiException {
        okhttp3.Call localVarCall = validationChecksStoreValidateBeforeCall(validationChecksStoreRequest, null);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a new validation check (asynchronously)
     * Create a new validation check entry.
     * @param validationChecksStoreRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Validation check created successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksStoreAsync(@javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest, final ApiCallback<ValidationCheck> _callback) throws ApiException {

        okhttp3.Call localVarCall = validationChecksStoreValidateBeforeCall(validationChecksStoreRequest, _callback);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for validationChecksUpdate
     * @param id ID of the validation check (required)
     * @param validationChecksStoreRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksUpdateCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = validationChecksStoreRequest;

        // create path and map variables
        String localVarPath = "/api/v1/validation_checks/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call validationChecksUpdateValidateBeforeCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling validationChecksUpdate(Async)");
        }

        // verify the required parameter 'validationChecksStoreRequest' is set
        if (validationChecksStoreRequest == null) {
            throw new ApiException("Missing the required parameter 'validationChecksStoreRequest' when calling validationChecksUpdate(Async)");
        }

        return validationChecksUpdateCall(id, validationChecksStoreRequest, _callback);

    }

    /**
     * Update a validation check
     * Edit an existing validation check.
     * @param id ID of the validation check (required)
     * @param validationChecksStoreRequest  (required)
     * @return ValidationCheck
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public ValidationCheck validationChecksUpdate(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest) throws ApiException {
        ApiResponse<ValidationCheck> localVarResp = validationChecksUpdateWithHttpInfo(id, validationChecksStoreRequest);
        return localVarResp.getData();
    }

    /**
     * Update a validation check
     * Edit an existing validation check.
     * @param id ID of the validation check (required)
     * @param validationChecksStoreRequest  (required)
     * @return ApiResponse&lt;ValidationCheck&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ValidationCheck> validationChecksUpdateWithHttpInfo(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest) throws ApiException {
        okhttp3.Call localVarCall = validationChecksUpdateValidateBeforeCall(id, validationChecksStoreRequest, null);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a validation check (asynchronously)
     * Edit an existing validation check.
     * @param id ID of the validation check (required)
     * @param validationChecksStoreRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Validation check updated successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid argument(s) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Validation check not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call validationChecksUpdateAsync(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull ValidationChecksStoreRequest validationChecksStoreRequest, final ApiCallback<ValidationCheck> _callback) throws ApiException {

        okhttp3.Call localVarCall = validationChecksUpdateValidateBeforeCall(id, validationChecksStoreRequest, _callback);
        Type localVarReturnType = new TypeToken<ValidationCheck>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
