/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * Affiliation model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-03T14:11:11.944970577Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class Affiliation {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_ORGANISATION_ID = "organisation_id";
  @SerializedName(SERIALIZED_NAME_ORGANISATION_ID)
  @javax.annotation.Nullable
  private Integer organisationId;

  public static final String SERIALIZED_NAME_MEMBER_ID = "member_id";
  @SerializedName(SERIALIZED_NAME_MEMBER_ID)
  @javax.annotation.Nullable
  private String memberId;

  public static final String SERIALIZED_NAME_RELATIONSHIP = "relationship";
  @SerializedName(SERIALIZED_NAME_RELATIONSHIP)
  @javax.annotation.Nullable
  private String relationship;

  public static final String SERIALIZED_NAME_FROM = "from";
  @SerializedName(SERIALIZED_NAME_FROM)
  @javax.annotation.Nullable
  private String from;

  public static final String SERIALIZED_NAME_TO = "to";
  @SerializedName(SERIALIZED_NAME_TO)
  @javax.annotation.Nullable
  private String to;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  @javax.annotation.Nullable
  private String department;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  @javax.annotation.Nullable
  private String role;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_ROR = "ror";
  @SerializedName(SERIALIZED_NAME_ROR)
  @javax.annotation.Nullable
  private String ror;

  public static final String SERIALIZED_NAME_REGISTRY_ID = "registry_id";
  @SerializedName(SERIALIZED_NAME_REGISTRY_ID)
  @javax.annotation.Nullable
  private Integer registryId;

  public static final String SERIALIZED_NAME_CURRENT_EMPLOYER = "current_employer";
  @SerializedName(SERIALIZED_NAME_CURRENT_EMPLOYER)
  @javax.annotation.Nullable
  private Boolean currentEmployer;

  public static final String SERIALIZED_NAME_VERIFICATION_CODE = "verification_code";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_CODE)
  @javax.annotation.Nullable
  private String verificationCode;

  public static final String SERIALIZED_NAME_VERIFICATION_SENT_AT = "verification_sent_at";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_SENT_AT)
  @javax.annotation.Nullable
  private OffsetDateTime verificationSentAt;

  public static final String SERIALIZED_NAME_VERIFICATION_CONFIRMED_AT = "verification_confirmed_at";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_CONFIRMED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime verificationConfirmedAt;

  public static final String SERIALIZED_NAME_IS_VERIFIED = "is_verified";
  @SerializedName(SERIALIZED_NAME_IS_VERIFIED)
  @javax.annotation.Nullable
  private Boolean isVerified;

  public Affiliation() {
  }

  public Affiliation id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Model primary key
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Affiliation createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public Affiliation updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Affiliation organisationId(@javax.annotation.Nullable Integer organisationId) {
    this.organisationId = organisationId;
    return this;
  }

  /**
   * Organisational link
   * @return organisationId
   */
  @javax.annotation.Nullable
  public Integer getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(@javax.annotation.Nullable Integer organisationId) {
    this.organisationId = organisationId;
  }


  public Affiliation memberId(@javax.annotation.Nullable String memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Member ID UUID
   * @return memberId
   */
  @javax.annotation.Nullable
  public String getMemberId() {
    return memberId;
  }

  public void setMemberId(@javax.annotation.Nullable String memberId) {
    this.memberId = memberId;
  }


  public Affiliation relationship(@javax.annotation.Nullable String relationship) {
    this.relationship = relationship;
    return this;
  }

  /**
   * Textual representation of affiliation relationship
   * @return relationship
   */
  @javax.annotation.Nullable
  public String getRelationship() {
    return relationship;
  }

  public void setRelationship(@javax.annotation.Nullable String relationship) {
    this.relationship = relationship;
  }


  public Affiliation from(@javax.annotation.Nullable String from) {
    this.from = from;
    return this;
  }

  /**
   * Date affiliation commenced
   * @return from
   */
  @javax.annotation.Nullable
  public String getFrom() {
    return from;
  }

  public void setFrom(@javax.annotation.Nullable String from) {
    this.from = from;
  }


  public Affiliation to(@javax.annotation.Nullable String to) {
    this.to = to;
    return this;
  }

  /**
   * Date affiliation concluded
   * @return to
   */
  @javax.annotation.Nullable
  public String getTo() {
    return to;
  }

  public void setTo(@javax.annotation.Nullable String to) {
    this.to = to;
  }


  public Affiliation department(@javax.annotation.Nullable String department) {
    this.department = department;
    return this;
  }

  /**
   * Department worked during affiliation
   * @return department
   */
  @javax.annotation.Nullable
  public String getDepartment() {
    return department;
  }

  public void setDepartment(@javax.annotation.Nullable String department) {
    this.department = department;
  }


  public Affiliation role(@javax.annotation.Nullable String role) {
    this.role = role;
    return this;
  }

  /**
   * Role held during affiliation
   * @return role
   */
  @javax.annotation.Nullable
  public String getRole() {
    return role;
  }

  public void setRole(@javax.annotation.Nullable String role) {
    this.role = role;
  }


  public Affiliation email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Professional email held during affiliation
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public Affiliation ror(@javax.annotation.Nullable String ror) {
    this.ror = ror;
    return this;
  }

  /**
   * The ROR.org identifier for this affiliation institute
   * @return ror
   */
  @javax.annotation.Nullable
  public String getRor() {
    return ror;
  }

  public void setRor(@javax.annotation.Nullable String ror) {
    this.ror = ror;
  }


  public Affiliation registryId(@javax.annotation.Nullable Integer registryId) {
    this.registryId = registryId;
    return this;
  }

  /**
   * The Registry primary key associated with this affiliation
   * @return registryId
   */
  @javax.annotation.Nullable
  public Integer getRegistryId() {
    return registryId;
  }

  public void setRegistryId(@javax.annotation.Nullable Integer registryId) {
    this.registryId = registryId;
  }


  public Affiliation currentEmployer(@javax.annotation.Nullable Boolean currentEmployer) {
    this.currentEmployer = currentEmployer;
    return this;
  }

  /**
   * Flag indicating if affiliation is for the current employer
   * @return currentEmployer
   */
  @javax.annotation.Nullable
  public Boolean getCurrentEmployer() {
    return currentEmployer;
  }

  public void setCurrentEmployer(@javax.annotation.Nullable Boolean currentEmployer) {
    this.currentEmployer = currentEmployer;
  }


  public Affiliation verificationCode(@javax.annotation.Nullable String verificationCode) {
    this.verificationCode = verificationCode;
    return this;
  }

  /**
   * Unique verification code issued for confirmation
   * @return verificationCode
   */
  @javax.annotation.Nullable
  public String getVerificationCode() {
    return verificationCode;
  }

  public void setVerificationCode(@javax.annotation.Nullable String verificationCode) {
    this.verificationCode = verificationCode;
  }


  public Affiliation verificationSentAt(@javax.annotation.Nullable OffsetDateTime verificationSentAt) {
    this.verificationSentAt = verificationSentAt;
    return this;
  }

  /**
   * Timestamp when verification code was sent
   * @return verificationSentAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getVerificationSentAt() {
    return verificationSentAt;
  }

  public void setVerificationSentAt(@javax.annotation.Nullable OffsetDateTime verificationSentAt) {
    this.verificationSentAt = verificationSentAt;
  }


  public Affiliation verificationConfirmedAt(@javax.annotation.Nullable OffsetDateTime verificationConfirmedAt) {
    this.verificationConfirmedAt = verificationConfirmedAt;
    return this;
  }

  /**
   * Timestamp when verification was confirmed
   * @return verificationConfirmedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getVerificationConfirmedAt() {
    return verificationConfirmedAt;
  }

  public void setVerificationConfirmedAt(@javax.annotation.Nullable OffsetDateTime verificationConfirmedAt) {
    this.verificationConfirmedAt = verificationConfirmedAt;
  }


  public Affiliation isVerified(@javax.annotation.Nullable Boolean isVerified) {
    this.isVerified = isVerified;
    return this;
  }

  /**
   * Flag indicating if affiliation is verified
   * @return isVerified
   */
  @javax.annotation.Nullable
  public Boolean getIsVerified() {
    return isVerified;
  }

  public void setIsVerified(@javax.annotation.Nullable Boolean isVerified) {
    this.isVerified = isVerified;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Affiliation affiliation = (Affiliation) o;
    return Objects.equals(this.id, affiliation.id) &&
        Objects.equals(this.createdAt, affiliation.createdAt) &&
        Objects.equals(this.updatedAt, affiliation.updatedAt) &&
        Objects.equals(this.organisationId, affiliation.organisationId) &&
        Objects.equals(this.memberId, affiliation.memberId) &&
        Objects.equals(this.relationship, affiliation.relationship) &&
        Objects.equals(this.from, affiliation.from) &&
        Objects.equals(this.to, affiliation.to) &&
        Objects.equals(this.department, affiliation.department) &&
        Objects.equals(this.role, affiliation.role) &&
        Objects.equals(this.email, affiliation.email) &&
        Objects.equals(this.ror, affiliation.ror) &&
        Objects.equals(this.registryId, affiliation.registryId) &&
        Objects.equals(this.currentEmployer, affiliation.currentEmployer) &&
        Objects.equals(this.verificationCode, affiliation.verificationCode) &&
        Objects.equals(this.verificationSentAt, affiliation.verificationSentAt) &&
        Objects.equals(this.verificationConfirmedAt, affiliation.verificationConfirmedAt) &&
        Objects.equals(this.isVerified, affiliation.isVerified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, organisationId, memberId, relationship, from, to, department, role, email, ror, registryId, currentEmployer, verificationCode, verificationSentAt, verificationConfirmedAt, isVerified);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Affiliation {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    relationship: ").append(toIndentedString(relationship)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    ror: ").append(toIndentedString(ror)).append("\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("    currentEmployer: ").append(toIndentedString(currentEmployer)).append("\n");
    sb.append("    verificationCode: ").append(toIndentedString(verificationCode)).append("\n");
    sb.append("    verificationSentAt: ").append(toIndentedString(verificationSentAt)).append("\n");
    sb.append("    verificationConfirmedAt: ").append(toIndentedString(verificationConfirmedAt)).append("\n");
    sb.append("    isVerified: ").append(toIndentedString(isVerified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created_at", "updated_at", "organisation_id", "member_id", "relationship", "from", "to", "department", "role", "email", "ror", "registry_id", "current_employer", "verification_code", "verification_sent_at", "verification_confirmed_at", "is_verified"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Affiliation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Affiliation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Affiliation is not found in the empty JSON string", Affiliation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Affiliation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Affiliation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if ((jsonObj.get("member_id") != null && !jsonObj.get("member_id").isJsonNull()) && !jsonObj.get("member_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `member_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("member_id").toString()));
      }
      if ((jsonObj.get("relationship") != null && !jsonObj.get("relationship").isJsonNull()) && !jsonObj.get("relationship").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `relationship` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relationship").toString()));
      }
      if ((jsonObj.get("from") != null && !jsonObj.get("from").isJsonNull()) && !jsonObj.get("from").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `from` to be a primitive type in the JSON string but got `%s`", jsonObj.get("from").toString()));
      }
      if ((jsonObj.get("to") != null && !jsonObj.get("to").isJsonNull()) && !jsonObj.get("to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("to").toString()));
      }
      if ((jsonObj.get("department") != null && !jsonObj.get("department").isJsonNull()) && !jsonObj.get("department").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `department` to be a primitive type in the JSON string but got `%s`", jsonObj.get("department").toString()));
      }
      if ((jsonObj.get("role") != null && !jsonObj.get("role").isJsonNull()) && !jsonObj.get("role").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `role` to be a primitive type in the JSON string but got `%s`", jsonObj.get("role").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("ror") != null && !jsonObj.get("ror").isJsonNull()) && !jsonObj.get("ror").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ror` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ror").toString()));
      }
      if ((jsonObj.get("verification_code") != null && !jsonObj.get("verification_code").isJsonNull()) && !jsonObj.get("verification_code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `verification_code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verification_code").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Affiliation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Affiliation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Affiliation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Affiliation.class));

       return (TypeAdapter<T>) new TypeAdapter<Affiliation>() {
           @Override
           public void write(JsonWriter out, Affiliation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Affiliation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Affiliation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Affiliation
   * @throws IOException if the JSON string is invalid with respect to Affiliation
   */
  public static Affiliation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Affiliation.class);
  }

  /**
   * Convert an instance of Affiliation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

