/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * CustodianGetProjectsUsers200ResponseDataDataInnerRegistry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-03T14:11:11.944970577Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class CustodianGetProjectsUsers200ResponseDataDataInnerRegistry {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_DIGI_IDENT = "digi_ident";
  @SerializedName(SERIALIZED_NAME_DIGI_IDENT)
  @javax.annotation.Nullable
  private String digiIdent;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  @javax.annotation.Nullable
  private Boolean verified;

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nullable
  private CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser user;

  public CustodianGetProjectsUsers200ResponseDataDataInnerRegistry() {
  }

  public CustodianGetProjectsUsers200ResponseDataDataInnerRegistry id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public CustodianGetProjectsUsers200ResponseDataDataInnerRegistry digiIdent(@javax.annotation.Nullable String digiIdent) {
    this.digiIdent = digiIdent;
    return this;
  }

  /**
   * Get digiIdent
   * @return digiIdent
   */
  @javax.annotation.Nullable
  public String getDigiIdent() {
    return digiIdent;
  }

  public void setDigiIdent(@javax.annotation.Nullable String digiIdent) {
    this.digiIdent = digiIdent;
  }


  public CustodianGetProjectsUsers200ResponseDataDataInnerRegistry verified(@javax.annotation.Nullable Boolean verified) {
    this.verified = verified;
    return this;
  }

  /**
   * Get verified
   * @return verified
   */
  @javax.annotation.Nullable
  public Boolean getVerified() {
    return verified;
  }

  public void setVerified(@javax.annotation.Nullable Boolean verified) {
    this.verified = verified;
  }


  public CustodianGetProjectsUsers200ResponseDataDataInnerRegistry user(@javax.annotation.Nullable CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  public CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser getUser() {
    return user;
  }

  public void setUser(@javax.annotation.Nullable CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser user) {
    this.user = user;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustodianGetProjectsUsers200ResponseDataDataInnerRegistry custodianGetProjectsUsers200ResponseDataDataInnerRegistry = (CustodianGetProjectsUsers200ResponseDataDataInnerRegistry) o;
    return Objects.equals(this.id, custodianGetProjectsUsers200ResponseDataDataInnerRegistry.id) &&
        Objects.equals(this.digiIdent, custodianGetProjectsUsers200ResponseDataDataInnerRegistry.digiIdent) &&
        Objects.equals(this.verified, custodianGetProjectsUsers200ResponseDataDataInnerRegistry.verified) &&
        Objects.equals(this.user, custodianGetProjectsUsers200ResponseDataDataInnerRegistry.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, digiIdent, verified, user);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustodianGetProjectsUsers200ResponseDataDataInnerRegistry {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    digiIdent: ").append(toIndentedString(digiIdent)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "digi_ident", "verified", "user"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustodianGetProjectsUsers200ResponseDataDataInnerRegistry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustodianGetProjectsUsers200ResponseDataDataInnerRegistry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CustodianGetProjectsUsers200ResponseDataDataInnerRegistry is not found in the empty JSON string", CustodianGetProjectsUsers200ResponseDataDataInnerRegistry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustodianGetProjectsUsers200ResponseDataDataInnerRegistry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CustodianGetProjectsUsers200ResponseDataDataInnerRegistry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("digi_ident") != null && !jsonObj.get("digi_ident").isJsonNull()) && !jsonObj.get("digi_ident").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `digi_ident` to be a primitive type in the JSON string but got `%s`", jsonObj.get("digi_ident").toString()));
      }
      // validate the optional field `user`
      if (jsonObj.get("user") != null && !jsonObj.get("user").isJsonNull()) {
        CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser.validateJsonElement(jsonObj.get("user"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustodianGetProjectsUsers200ResponseDataDataInnerRegistry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustodianGetProjectsUsers200ResponseDataDataInnerRegistry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustodianGetProjectsUsers200ResponseDataDataInnerRegistry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustodianGetProjectsUsers200ResponseDataDataInnerRegistry.class));

       return (TypeAdapter<T>) new TypeAdapter<CustodianGetProjectsUsers200ResponseDataDataInnerRegistry>() {
           @Override
           public void write(JsonWriter out, CustodianGetProjectsUsers200ResponseDataDataInnerRegistry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustodianGetProjectsUsers200ResponseDataDataInnerRegistry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustodianGetProjectsUsers200ResponseDataDataInnerRegistry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustodianGetProjectsUsers200ResponseDataDataInnerRegistry
   * @throws IOException if the JSON string is invalid with respect to CustodianGetProjectsUsers200ResponseDataDataInnerRegistry
   */
  public static CustodianGetProjectsUsers200ResponseDataDataInnerRegistry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustodianGetProjectsUsers200ResponseDataDataInnerRegistry.class);
  }

  /**
   * Convert an instance of CustodianGetProjectsUsers200ResponseDataDataInnerRegistry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

