/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * HistoryIndex200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-03T14:11:11.944970577Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class HistoryIndex200ResponseData {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_ENDORSEMENT_ID = "endorsement_id";
  @SerializedName(SERIALIZED_NAME_ENDORSEMENT_ID)
  @javax.annotation.Nullable
  private Integer endorsementId;

  public static final String SERIALIZED_NAME_INFRINGEMENT_ID = "infringement_id";
  @SerializedName(SERIALIZED_NAME_INFRINGEMENT_ID)
  @javax.annotation.Nullable
  private Integer infringementId;

  public static final String SERIALIZED_NAME_PROJECT_ID = "project_id";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String SERIALIZED_NAME_ACCESS_KEY_ID = "access_key_id";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY_ID)
  @javax.annotation.Nullable
  private Integer accessKeyId;

  public static final String SERIALIZED_NAME_CUSTODIAN_IDENTIFIER = "custodian_identifier";
  @SerializedName(SERIALIZED_NAME_CUSTODIAN_IDENTIFIER)
  @javax.annotation.Nullable
  private String custodianIdentifier;

  public HistoryIndex200ResponseData() {
  }

  public HistoryIndex200ResponseData id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public HistoryIndex200ResponseData createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public HistoryIndex200ResponseData updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public HistoryIndex200ResponseData endorsementId(@javax.annotation.Nullable Integer endorsementId) {
    this.endorsementId = endorsementId;
    return this;
  }

  /**
   * Get endorsementId
   * @return endorsementId
   */
  @javax.annotation.Nullable
  public Integer getEndorsementId() {
    return endorsementId;
  }

  public void setEndorsementId(@javax.annotation.Nullable Integer endorsementId) {
    this.endorsementId = endorsementId;
  }


  public HistoryIndex200ResponseData infringementId(@javax.annotation.Nullable Integer infringementId) {
    this.infringementId = infringementId;
    return this;
  }

  /**
   * Get infringementId
   * @return infringementId
   */
  @javax.annotation.Nullable
  public Integer getInfringementId() {
    return infringementId;
  }

  public void setInfringementId(@javax.annotation.Nullable Integer infringementId) {
    this.infringementId = infringementId;
  }


  public HistoryIndex200ResponseData projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @javax.annotation.Nullable
  public Integer getProjectId() {
    return projectId;
  }

  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public HistoryIndex200ResponseData accessKeyId(@javax.annotation.Nullable Integer accessKeyId) {
    this.accessKeyId = accessKeyId;
    return this;
  }

  /**
   * Get accessKeyId
   * @return accessKeyId
   */
  @javax.annotation.Nullable
  public Integer getAccessKeyId() {
    return accessKeyId;
  }

  public void setAccessKeyId(@javax.annotation.Nullable Integer accessKeyId) {
    this.accessKeyId = accessKeyId;
  }


  public HistoryIndex200ResponseData custodianIdentifier(@javax.annotation.Nullable String custodianIdentifier) {
    this.custodianIdentifier = custodianIdentifier;
    return this;
  }

  /**
   * Get custodianIdentifier
   * @return custodianIdentifier
   */
  @javax.annotation.Nullable
  public String getCustodianIdentifier() {
    return custodianIdentifier;
  }

  public void setCustodianIdentifier(@javax.annotation.Nullable String custodianIdentifier) {
    this.custodianIdentifier = custodianIdentifier;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HistoryIndex200ResponseData historyIndex200ResponseData = (HistoryIndex200ResponseData) o;
    return Objects.equals(this.id, historyIndex200ResponseData.id) &&
        Objects.equals(this.createdAt, historyIndex200ResponseData.createdAt) &&
        Objects.equals(this.updatedAt, historyIndex200ResponseData.updatedAt) &&
        Objects.equals(this.endorsementId, historyIndex200ResponseData.endorsementId) &&
        Objects.equals(this.infringementId, historyIndex200ResponseData.infringementId) &&
        Objects.equals(this.projectId, historyIndex200ResponseData.projectId) &&
        Objects.equals(this.accessKeyId, historyIndex200ResponseData.accessKeyId) &&
        Objects.equals(this.custodianIdentifier, historyIndex200ResponseData.custodianIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, endorsementId, infringementId, projectId, accessKeyId, custodianIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HistoryIndex200ResponseData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    endorsementId: ").append(toIndentedString(endorsementId)).append("\n");
    sb.append("    infringementId: ").append(toIndentedString(infringementId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    custodianIdentifier: ").append(toIndentedString(custodianIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created_at", "updated_at", "endorsement_id", "infringement_id", "project_id", "access_key_id", "custodian_identifier"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HistoryIndex200ResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HistoryIndex200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HistoryIndex200ResponseData is not found in the empty JSON string", HistoryIndex200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HistoryIndex200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HistoryIndex200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if ((jsonObj.get("custodian_identifier") != null && !jsonObj.get("custodian_identifier").isJsonNull()) && !jsonObj.get("custodian_identifier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `custodian_identifier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("custodian_identifier").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HistoryIndex200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HistoryIndex200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HistoryIndex200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HistoryIndex200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<HistoryIndex200ResponseData>() {
           @Override
           public void write(JsonWriter out, HistoryIndex200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HistoryIndex200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HistoryIndex200ResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HistoryIndex200ResponseData
   * @throws IOException if the JSON string is invalid with respect to HistoryIndex200ResponseData
   */
  public static HistoryIndex200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HistoryIndex200ResponseData.class);
  }

  /**
   * Convert an instance of HistoryIndex200ResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

