/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * OrganisationsIdvt200ResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-03T14:11:11.944970577Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class OrganisationsIdvt200ResponseData {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_IDVT_RESULT = "idvt_result";
  @SerializedName(SERIALIZED_NAME_IDVT_RESULT)
  @javax.annotation.Nullable
  private Boolean idvtResult;

  public static final String SERIALIZED_NAME_IDVT_RESULT_PERC = "idvt_result_perc";
  @SerializedName(SERIALIZED_NAME_IDVT_RESULT_PERC)
  @javax.annotation.Nullable
  private BigDecimal idvtResultPerc;

  public static final String SERIALIZED_NAME_IDVT_ERRORS = "idvt_errors";
  @SerializedName(SERIALIZED_NAME_IDVT_ERRORS)
  @javax.annotation.Nullable
  private Object idvtErrors;

  public static final String SERIALIZED_NAME_IDVT_COMPLETED_AT = "idvt_completed_at";
  @SerializedName(SERIALIZED_NAME_IDVT_COMPLETED_AT)
  @javax.annotation.Nullable
  private String idvtCompletedAt;

  public OrganisationsIdvt200ResponseData() {
  }

  public OrganisationsIdvt200ResponseData id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public OrganisationsIdvt200ResponseData idvtResult(@javax.annotation.Nullable Boolean idvtResult) {
    this.idvtResult = idvtResult;
    return this;
  }

  /**
   * Get idvtResult
   * @return idvtResult
   */
  @javax.annotation.Nullable
  public Boolean getIdvtResult() {
    return idvtResult;
  }

  public void setIdvtResult(@javax.annotation.Nullable Boolean idvtResult) {
    this.idvtResult = idvtResult;
  }


  public OrganisationsIdvt200ResponseData idvtResultPerc(@javax.annotation.Nullable BigDecimal idvtResultPerc) {
    this.idvtResultPerc = idvtResultPerc;
    return this;
  }

  /**
   * Get idvtResultPerc
   * @return idvtResultPerc
   */
  @javax.annotation.Nullable
  public BigDecimal getIdvtResultPerc() {
    return idvtResultPerc;
  }

  public void setIdvtResultPerc(@javax.annotation.Nullable BigDecimal idvtResultPerc) {
    this.idvtResultPerc = idvtResultPerc;
  }


  public OrganisationsIdvt200ResponseData idvtErrors(@javax.annotation.Nullable Object idvtErrors) {
    this.idvtErrors = idvtErrors;
    return this;
  }

  /**
   * Get idvtErrors
   * @return idvtErrors
   */
  @javax.annotation.Nullable
  public Object getIdvtErrors() {
    return idvtErrors;
  }

  public void setIdvtErrors(@javax.annotation.Nullable Object idvtErrors) {
    this.idvtErrors = idvtErrors;
  }


  public OrganisationsIdvt200ResponseData idvtCompletedAt(@javax.annotation.Nullable String idvtCompletedAt) {
    this.idvtCompletedAt = idvtCompletedAt;
    return this;
  }

  /**
   * Get idvtCompletedAt
   * @return idvtCompletedAt
   */
  @javax.annotation.Nullable
  public String getIdvtCompletedAt() {
    return idvtCompletedAt;
  }

  public void setIdvtCompletedAt(@javax.annotation.Nullable String idvtCompletedAt) {
    this.idvtCompletedAt = idvtCompletedAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganisationsIdvt200ResponseData organisationsIdvt200ResponseData = (OrganisationsIdvt200ResponseData) o;
    return Objects.equals(this.id, organisationsIdvt200ResponseData.id) &&
        Objects.equals(this.idvtResult, organisationsIdvt200ResponseData.idvtResult) &&
        Objects.equals(this.idvtResultPerc, organisationsIdvt200ResponseData.idvtResultPerc) &&
        Objects.equals(this.idvtErrors, organisationsIdvt200ResponseData.idvtErrors) &&
        Objects.equals(this.idvtCompletedAt, organisationsIdvt200ResponseData.idvtCompletedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, idvtResult, idvtResultPerc, idvtErrors, idvtCompletedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrganisationsIdvt200ResponseData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idvtResult: ").append(toIndentedString(idvtResult)).append("\n");
    sb.append("    idvtResultPerc: ").append(toIndentedString(idvtResultPerc)).append("\n");
    sb.append("    idvtErrors: ").append(toIndentedString(idvtErrors)).append("\n");
    sb.append("    idvtCompletedAt: ").append(toIndentedString(idvtCompletedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "idvt_result", "idvt_result_perc", "idvt_errors", "idvt_completed_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OrganisationsIdvt200ResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OrganisationsIdvt200ResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in OrganisationsIdvt200ResponseData is not found in the empty JSON string", OrganisationsIdvt200ResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OrganisationsIdvt200ResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `OrganisationsIdvt200ResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("idvt_completed_at") != null && !jsonObj.get("idvt_completed_at").isJsonNull()) && !jsonObj.get("idvt_completed_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `idvt_completed_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("idvt_completed_at").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OrganisationsIdvt200ResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OrganisationsIdvt200ResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OrganisationsIdvt200ResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OrganisationsIdvt200ResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<OrganisationsIdvt200ResponseData>() {
           @Override
           public void write(JsonWriter out, OrganisationsIdvt200ResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OrganisationsIdvt200ResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OrganisationsIdvt200ResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OrganisationsIdvt200ResponseData
   * @throws IOException if the JSON string is invalid with respect to OrganisationsIdvt200ResponseData
   */
  public static OrganisationsIdvt200ResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OrganisationsIdvt200ResponseData.class);
  }

  /**
   * Convert an instance of OrganisationsIdvt200ResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

