/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * ProjectUsersBulkInviteProjectUsersRequestUsersInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-05T05:12:22.471719795Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class ProjectUsersBulkInviteProjectUsersRequestUsersInner {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  @javax.annotation.Nullable
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  @javax.annotation.Nullable
  private String lastName;

  public static final String SERIALIZED_NAME_EMAIL_ADDRESS = "emailAddress";
  @SerializedName(SERIALIZED_NAME_EMAIL_ADDRESS)
  @javax.annotation.Nullable
  private String emailAddress;

  /**
   * Gets or Sets projectRole
   */
  @JsonAdapter(ProjectRoleEnum.Adapter.class)
  public enum ProjectRoleEnum {
    PRINCIPAL_INVESTIGATOR_PI_("Principal Investigator (PI)"),
    
    CO_INVESTIGATOR_CO_I_SUB_INVESTIGATOR_SUB_I_("Co-Investigator (Co-I) / Sub-Investigator (Sub-I)"),
    
    DATA_ANALYST("Data Analyst"),
    
    DATA_ENGINEER("Data Engineer"),
    
    POSTDOC("Postdoc"),
    
    RESEARCH_FELLOW("Research Fellow"),
    
    RESEARCHER("Researcher"),
    
    STUDENT("Student");

    private String value;

    ProjectRoleEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProjectRoleEnum fromValue(String value) {
      for (ProjectRoleEnum b : ProjectRoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProjectRoleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProjectRoleEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProjectRoleEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProjectRoleEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProjectRoleEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PROJECT_ROLE = "projectRole";
  @SerializedName(SERIALIZED_NAME_PROJECT_ROLE)
  @javax.annotation.Nullable
  private ProjectRoleEnum projectRole;

  public static final String SERIALIZED_NAME_ORGANISATION_ID = "organisationId";
  @SerializedName(SERIALIZED_NAME_ORGANISATION_ID)
  @javax.annotation.Nullable
  private Integer organisationId;

  public ProjectUsersBulkInviteProjectUsersRequestUsersInner() {
  }

  public ProjectUsersBulkInviteProjectUsersRequestUsersInner firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @javax.annotation.Nullable
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public ProjectUsersBulkInviteProjectUsersRequestUsersInner lastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @javax.annotation.Nullable
  public String getLastName() {
    return lastName;
  }

  public void setLastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }


  public ProjectUsersBulkInviteProjectUsersRequestUsersInner emailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * Get emailAddress
   * @return emailAddress
   */
  @javax.annotation.Nullable
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(@javax.annotation.Nullable String emailAddress) {
    this.emailAddress = emailAddress;
  }


  public ProjectUsersBulkInviteProjectUsersRequestUsersInner projectRole(@javax.annotation.Nullable ProjectRoleEnum projectRole) {
    this.projectRole = projectRole;
    return this;
  }

  /**
   * Get projectRole
   * @return projectRole
   */
  @javax.annotation.Nullable
  public ProjectRoleEnum getProjectRole() {
    return projectRole;
  }

  public void setProjectRole(@javax.annotation.Nullable ProjectRoleEnum projectRole) {
    this.projectRole = projectRole;
  }


  public ProjectUsersBulkInviteProjectUsersRequestUsersInner organisationId(@javax.annotation.Nullable Integer organisationId) {
    this.organisationId = organisationId;
    return this;
  }

  /**
   * Get organisationId
   * @return organisationId
   */
  @javax.annotation.Nullable
  public Integer getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(@javax.annotation.Nullable Integer organisationId) {
    this.organisationId = organisationId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectUsersBulkInviteProjectUsersRequestUsersInner projectUsersBulkInviteProjectUsersRequestUsersInner = (ProjectUsersBulkInviteProjectUsersRequestUsersInner) o;
    return Objects.equals(this.firstName, projectUsersBulkInviteProjectUsersRequestUsersInner.firstName) &&
        Objects.equals(this.lastName, projectUsersBulkInviteProjectUsersRequestUsersInner.lastName) &&
        Objects.equals(this.emailAddress, projectUsersBulkInviteProjectUsersRequestUsersInner.emailAddress) &&
        Objects.equals(this.projectRole, projectUsersBulkInviteProjectUsersRequestUsersInner.projectRole) &&
        Objects.equals(this.organisationId, projectUsersBulkInviteProjectUsersRequestUsersInner.organisationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, emailAddress, projectRole, organisationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectUsersBulkInviteProjectUsersRequestUsersInner {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    projectRole: ").append(toIndentedString(projectRole)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("firstName", "lastName", "emailAddress", "projectRole", "organisationId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectUsersBulkInviteProjectUsersRequestUsersInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectUsersBulkInviteProjectUsersRequestUsersInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ProjectUsersBulkInviteProjectUsersRequestUsersInner is not found in the empty JSON string", ProjectUsersBulkInviteProjectUsersRequestUsersInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectUsersBulkInviteProjectUsersRequestUsersInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectUsersBulkInviteProjectUsersRequestUsersInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("firstName") != null && !jsonObj.get("firstName").isJsonNull()) && !jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if ((jsonObj.get("lastName") != null && !jsonObj.get("lastName").isJsonNull()) && !jsonObj.get("lastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `lastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName").toString()));
      }
      if ((jsonObj.get("emailAddress") != null && !jsonObj.get("emailAddress").isJsonNull()) && !jsonObj.get("emailAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `emailAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("emailAddress").toString()));
      }
      if ((jsonObj.get("projectRole") != null && !jsonObj.get("projectRole").isJsonNull()) && !jsonObj.get("projectRole").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `projectRole` to be a primitive type in the JSON string but got `%s`", jsonObj.get("projectRole").toString()));
      }
      // validate the optional field `projectRole`
      if (jsonObj.get("projectRole") != null && !jsonObj.get("projectRole").isJsonNull()) {
        ProjectRoleEnum.validateJsonElement(jsonObj.get("projectRole"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectUsersBulkInviteProjectUsersRequestUsersInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectUsersBulkInviteProjectUsersRequestUsersInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectUsersBulkInviteProjectUsersRequestUsersInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectUsersBulkInviteProjectUsersRequestUsersInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectUsersBulkInviteProjectUsersRequestUsersInner>() {
           @Override
           public void write(JsonWriter out, ProjectUsersBulkInviteProjectUsersRequestUsersInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectUsersBulkInviteProjectUsersRequestUsersInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectUsersBulkInviteProjectUsersRequestUsersInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectUsersBulkInviteProjectUsersRequestUsersInner
   * @throws IOException if the JSON string is invalid with respect to ProjectUsersBulkInviteProjectUsersRequestUsersInner
   */
  public static ProjectUsersBulkInviteProjectUsersRequestUsersInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectUsersBulkInviteProjectUsersRequestUsersInner.class);
  }

  /**
   * Convert an instance of ProjectUsersBulkInviteProjectUsersRequestUsersInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

