/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import uk.ac.hdruk.safepeopleregistryapi.model.ProjectUpdateAllProjectUsersRequestUsersInnerRole;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * ProjectUpdateAllProjectUsersRequestUsersInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-03T14:11:11.944970577Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class ProjectUpdateAllProjectUsersRequestUsersInner {
  public static final String SERIALIZED_NAME_REGISTRY_ID = "registry_id";
  @SerializedName(SERIALIZED_NAME_REGISTRY_ID)
  @javax.annotation.Nullable
  private Integer registryId;

  public static final String SERIALIZED_NAME_AFFILIATION_ID = "affiliation_id";
  @SerializedName(SERIALIZED_NAME_AFFILIATION_ID)
  @javax.annotation.Nullable
  private Integer affiliationId;

  public static final String SERIALIZED_NAME_PROJECT_USER_ID = "project_user_id";
  @SerializedName(SERIALIZED_NAME_PROJECT_USER_ID)
  @javax.annotation.Nullable
  private Integer projectUserId;

  public static final String SERIALIZED_NAME_PRIMARY_CONTACT = "primary_contact";
  @SerializedName(SERIALIZED_NAME_PRIMARY_CONTACT)
  @javax.annotation.Nullable
  private Boolean primaryContact;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  @javax.annotation.Nullable
  private ProjectUpdateAllProjectUsersRequestUsersInnerRole role;

  public ProjectUpdateAllProjectUsersRequestUsersInner() {
  }

  public ProjectUpdateAllProjectUsersRequestUsersInner registryId(@javax.annotation.Nullable Integer registryId) {
    this.registryId = registryId;
    return this;
  }

  /**
   * Get registryId
   * @return registryId
   */
  @javax.annotation.Nullable
  public Integer getRegistryId() {
    return registryId;
  }

  public void setRegistryId(@javax.annotation.Nullable Integer registryId) {
    this.registryId = registryId;
  }


  public ProjectUpdateAllProjectUsersRequestUsersInner affiliationId(@javax.annotation.Nullable Integer affiliationId) {
    this.affiliationId = affiliationId;
    return this;
  }

  /**
   * Get affiliationId
   * @return affiliationId
   */
  @javax.annotation.Nullable
  public Integer getAffiliationId() {
    return affiliationId;
  }

  public void setAffiliationId(@javax.annotation.Nullable Integer affiliationId) {
    this.affiliationId = affiliationId;
  }


  public ProjectUpdateAllProjectUsersRequestUsersInner projectUserId(@javax.annotation.Nullable Integer projectUserId) {
    this.projectUserId = projectUserId;
    return this;
  }

  /**
   * Get projectUserId
   * @return projectUserId
   */
  @javax.annotation.Nullable
  public Integer getProjectUserId() {
    return projectUserId;
  }

  public void setProjectUserId(@javax.annotation.Nullable Integer projectUserId) {
    this.projectUserId = projectUserId;
  }


  public ProjectUpdateAllProjectUsersRequestUsersInner primaryContact(@javax.annotation.Nullable Boolean primaryContact) {
    this.primaryContact = primaryContact;
    return this;
  }

  /**
   * Get primaryContact
   * @return primaryContact
   */
  @javax.annotation.Nullable
  public Boolean getPrimaryContact() {
    return primaryContact;
  }

  public void setPrimaryContact(@javax.annotation.Nullable Boolean primaryContact) {
    this.primaryContact = primaryContact;
  }


  public ProjectUpdateAllProjectUsersRequestUsersInner role(@javax.annotation.Nullable ProjectUpdateAllProjectUsersRequestUsersInnerRole role) {
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable
  public ProjectUpdateAllProjectUsersRequestUsersInnerRole getRole() {
    return role;
  }

  public void setRole(@javax.annotation.Nullable ProjectUpdateAllProjectUsersRequestUsersInnerRole role) {
    this.role = role;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectUpdateAllProjectUsersRequestUsersInner projectUpdateAllProjectUsersRequestUsersInner = (ProjectUpdateAllProjectUsersRequestUsersInner) o;
    return Objects.equals(this.registryId, projectUpdateAllProjectUsersRequestUsersInner.registryId) &&
        Objects.equals(this.affiliationId, projectUpdateAllProjectUsersRequestUsersInner.affiliationId) &&
        Objects.equals(this.projectUserId, projectUpdateAllProjectUsersRequestUsersInner.projectUserId) &&
        Objects.equals(this.primaryContact, projectUpdateAllProjectUsersRequestUsersInner.primaryContact) &&
        Objects.equals(this.role, projectUpdateAllProjectUsersRequestUsersInner.role);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(registryId, affiliationId, projectUserId, primaryContact, role);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectUpdateAllProjectUsersRequestUsersInner {\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("    affiliationId: ").append(toIndentedString(affiliationId)).append("\n");
    sb.append("    projectUserId: ").append(toIndentedString(projectUserId)).append("\n");
    sb.append("    primaryContact: ").append(toIndentedString(primaryContact)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("registry_id", "affiliation_id", "project_user_id", "primary_contact", "role"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectUpdateAllProjectUsersRequestUsersInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectUpdateAllProjectUsersRequestUsersInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ProjectUpdateAllProjectUsersRequestUsersInner is not found in the empty JSON string", ProjectUpdateAllProjectUsersRequestUsersInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectUpdateAllProjectUsersRequestUsersInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectUpdateAllProjectUsersRequestUsersInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `role`
      if (jsonObj.get("role") != null && !jsonObj.get("role").isJsonNull()) {
        ProjectUpdateAllProjectUsersRequestUsersInnerRole.validateJsonElement(jsonObj.get("role"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectUpdateAllProjectUsersRequestUsersInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectUpdateAllProjectUsersRequestUsersInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectUpdateAllProjectUsersRequestUsersInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectUpdateAllProjectUsersRequestUsersInner.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectUpdateAllProjectUsersRequestUsersInner>() {
           @Override
           public void write(JsonWriter out, ProjectUpdateAllProjectUsersRequestUsersInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectUpdateAllProjectUsersRequestUsersInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectUpdateAllProjectUsersRequestUsersInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectUpdateAllProjectUsersRequestUsersInner
   * @throws IOException if the JSON string is invalid with respect to ProjectUpdateAllProjectUsersRequestUsersInner
   */
  public static ProjectUpdateAllProjectUsersRequestUsersInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectUpdateAllProjectUsersRequestUsersInner.class);
  }

  /**
   * Convert an instance of ProjectUpdateAllProjectUsersRequestUsersInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

