/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * Pivot model representing the relationship between projects and custodians
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-18T08:34:20.150560795Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class ProjectHasCustodian {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_PROJECT_ID = "project_id";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  @javax.annotation.Nullable
  private Integer projectId;

  public static final String SERIALIZED_NAME_CUSTODIAN_ID = "custodian_id";
  @SerializedName(SERIALIZED_NAME_CUSTODIAN_ID)
  @javax.annotation.Nullable
  private Integer custodianId;

  public static final String SERIALIZED_NAME_APPROVED = "approved";
  @SerializedName(SERIALIZED_NAME_APPROVED)
  @javax.annotation.Nullable
  private Integer approved;

  public ProjectHasCustodian() {
  }

  public ProjectHasCustodian id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the project-custodian relationship
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public ProjectHasCustodian projectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * ID of the project
   * @return projectId
   */
  @javax.annotation.Nullable
  public Integer getProjectId() {
    return projectId;
  }

  public void setProjectId(@javax.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public ProjectHasCustodian custodianId(@javax.annotation.Nullable Integer custodianId) {
    this.custodianId = custodianId;
    return this;
  }

  /**
   * ID of the custodian
   * @return custodianId
   */
  @javax.annotation.Nullable
  public Integer getCustodianId() {
    return custodianId;
  }

  public void setCustodianId(@javax.annotation.Nullable Integer custodianId) {
    this.custodianId = custodianId;
  }


  public ProjectHasCustodian approved(@javax.annotation.Nullable Integer approved) {
    this.approved = approved;
    return this;
  }

  /**
   * Indicates whether the custodian is approved for the project (1 for approved, 0 for not approved)
   * @return approved
   */
  @javax.annotation.Nullable
  public Integer getApproved() {
    return approved;
  }

  public void setApproved(@javax.annotation.Nullable Integer approved) {
    this.approved = approved;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectHasCustodian projectHasCustodian = (ProjectHasCustodian) o;
    return Objects.equals(this.id, projectHasCustodian.id) &&
        Objects.equals(this.projectId, projectHasCustodian.projectId) &&
        Objects.equals(this.custodianId, projectHasCustodian.custodianId) &&
        Objects.equals(this.approved, projectHasCustodian.approved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, projectId, custodianId, approved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectHasCustodian {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    custodianId: ").append(toIndentedString(custodianId)).append("\n");
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "project_id", "custodian_id", "approved"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ProjectHasCustodian
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProjectHasCustodian.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ProjectHasCustodian is not found in the empty JSON string", ProjectHasCustodian.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProjectHasCustodian.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ProjectHasCustodian` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectHasCustodian.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectHasCustodian' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectHasCustodian> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectHasCustodian.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectHasCustodian>() {
           @Override
           public void write(JsonWriter out, ProjectHasCustodian value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectHasCustodian read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ProjectHasCustodian given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ProjectHasCustodian
   * @throws IOException if the JSON string is invalid with respect to ProjectHasCustodian
   */
  public static ProjectHasCustodian fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectHasCustodian.class);
  }

  /**
   * Convert an instance of ProjectHasCustodian to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

