/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.safepeopleregistryapi.model.QueryQuery200ResponseDataRegistryAllOfHistoryInner;
import uk.ac.hdruk.safepeopleregistryapi.model.Training;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * The matched Registry record
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-03T14:11:11.944970577Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class QueryQuery200ResponseDataRegistry {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_DELETED_AT = "deleted_at";
  @SerializedName(SERIALIZED_NAME_DELETED_AT)
  @javax.annotation.Nullable
  private String deletedAt;

  public static final String SERIALIZED_NAME_DIGI_IDENT = "digi_ident";
  @SerializedName(SERIALIZED_NAME_DIGI_IDENT)
  @javax.annotation.Nullable
  private String digiIdent;

  public static final String SERIALIZED_NAME_DL_IDENT = "dl_ident";
  @SerializedName(SERIALIZED_NAME_DL_IDENT)
  @javax.annotation.Nullable
  private String dlIdent;

  public static final String SERIALIZED_NAME_PP_IDENT = "pp_ident";
  @SerializedName(SERIALIZED_NAME_PP_IDENT)
  @javax.annotation.Nullable
  private String ppIdent;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  @javax.annotation.Nullable
  private Integer verified;

  public static final String SERIALIZED_NAME_TRAINING = "training";
  @SerializedName(SERIALIZED_NAME_TRAINING)
  @javax.annotation.Nullable
  private List<Training> training = new ArrayList<>();

  public static final String SERIALIZED_NAME_HISTORY = "history";
  @SerializedName(SERIALIZED_NAME_HISTORY)
  @javax.annotation.Nullable
  private List<QueryQuery200ResponseDataRegistryAllOfHistoryInner> history = new ArrayList<>();

  public QueryQuery200ResponseDataRegistry() {
  }

  public QueryQuery200ResponseDataRegistry id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public QueryQuery200ResponseDataRegistry createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public QueryQuery200ResponseDataRegistry updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public QueryQuery200ResponseDataRegistry deletedAt(@javax.annotation.Nullable String deletedAt) {
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @javax.annotation.Nullable
  public String getDeletedAt() {
    return deletedAt;
  }

  public void setDeletedAt(@javax.annotation.Nullable String deletedAt) {
    this.deletedAt = deletedAt;
  }


  public QueryQuery200ResponseDataRegistry digiIdent(@javax.annotation.Nullable String digiIdent) {
    this.digiIdent = digiIdent;
    return this;
  }

  /**
   * Get digiIdent
   * @return digiIdent
   */
  @javax.annotation.Nullable
  public String getDigiIdent() {
    return digiIdent;
  }

  public void setDigiIdent(@javax.annotation.Nullable String digiIdent) {
    this.digiIdent = digiIdent;
  }


  public QueryQuery200ResponseDataRegistry dlIdent(@javax.annotation.Nullable String dlIdent) {
    this.dlIdent = dlIdent;
    return this;
  }

  /**
   * Get dlIdent
   * @return dlIdent
   */
  @javax.annotation.Nullable
  public String getDlIdent() {
    return dlIdent;
  }

  public void setDlIdent(@javax.annotation.Nullable String dlIdent) {
    this.dlIdent = dlIdent;
  }


  public QueryQuery200ResponseDataRegistry ppIdent(@javax.annotation.Nullable String ppIdent) {
    this.ppIdent = ppIdent;
    return this;
  }

  /**
   * Get ppIdent
   * @return ppIdent
   */
  @javax.annotation.Nullable
  public String getPpIdent() {
    return ppIdent;
  }

  public void setPpIdent(@javax.annotation.Nullable String ppIdent) {
    this.ppIdent = ppIdent;
  }


  public QueryQuery200ResponseDataRegistry verified(@javax.annotation.Nullable Integer verified) {
    this.verified = verified;
    return this;
  }

  /**
   * Get verified
   * @return verified
   */
  @javax.annotation.Nullable
  public Integer getVerified() {
    return verified;
  }

  public void setVerified(@javax.annotation.Nullable Integer verified) {
    this.verified = verified;
  }


  public QueryQuery200ResponseDataRegistry training(@javax.annotation.Nullable List<Training> training) {
    this.training = training;
    return this;
  }

  public QueryQuery200ResponseDataRegistry addTrainingItem(Training trainingItem) {
    if (this.training == null) {
      this.training = new ArrayList<>();
    }
    this.training.add(trainingItem);
    return this;
  }

  /**
   * Training records linked to the registry
   * @return training
   */
  @javax.annotation.Nullable
  public List<Training> getTraining() {
    return training;
  }

  public void setTraining(@javax.annotation.Nullable List<Training> training) {
    this.training = training;
  }


  public QueryQuery200ResponseDataRegistry history(@javax.annotation.Nullable List<QueryQuery200ResponseDataRegistryAllOfHistoryInner> history) {
    this.history = history;
    return this;
  }

  public QueryQuery200ResponseDataRegistry addHistoryItem(QueryQuery200ResponseDataRegistryAllOfHistoryInner historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<>();
    }
    this.history.add(historyItem);
    return this;
  }

  /**
   * History records linked to the registry, each with its related affiliation and project
   * @return history
   */
  @javax.annotation.Nullable
  public List<QueryQuery200ResponseDataRegistryAllOfHistoryInner> getHistory() {
    return history;
  }

  public void setHistory(@javax.annotation.Nullable List<QueryQuery200ResponseDataRegistryAllOfHistoryInner> history) {
    this.history = history;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryQuery200ResponseDataRegistry queryQuery200ResponseDataRegistry = (QueryQuery200ResponseDataRegistry) o;
    return Objects.equals(this.id, queryQuery200ResponseDataRegistry.id) &&
        Objects.equals(this.createdAt, queryQuery200ResponseDataRegistry.createdAt) &&
        Objects.equals(this.updatedAt, queryQuery200ResponseDataRegistry.updatedAt) &&
        Objects.equals(this.deletedAt, queryQuery200ResponseDataRegistry.deletedAt) &&
        Objects.equals(this.digiIdent, queryQuery200ResponseDataRegistry.digiIdent) &&
        Objects.equals(this.dlIdent, queryQuery200ResponseDataRegistry.dlIdent) &&
        Objects.equals(this.ppIdent, queryQuery200ResponseDataRegistry.ppIdent) &&
        Objects.equals(this.verified, queryQuery200ResponseDataRegistry.verified) &&
        Objects.equals(this.training, queryQuery200ResponseDataRegistry.training) &&
        Objects.equals(this.history, queryQuery200ResponseDataRegistry.history);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, deletedAt, digiIdent, dlIdent, ppIdent, verified, training, history);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryQuery200ResponseDataRegistry {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    digiIdent: ").append(toIndentedString(digiIdent)).append("\n");
    sb.append("    dlIdent: ").append(toIndentedString(dlIdent)).append("\n");
    sb.append("    ppIdent: ").append(toIndentedString(ppIdent)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    training: ").append(toIndentedString(training)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created_at", "updated_at", "deleted_at", "digi_ident", "dl_ident", "pp_ident", "verified", "training", "history"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QueryQuery200ResponseDataRegistry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QueryQuery200ResponseDataRegistry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in QueryQuery200ResponseDataRegistry is not found in the empty JSON string", QueryQuery200ResponseDataRegistry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QueryQuery200ResponseDataRegistry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `QueryQuery200ResponseDataRegistry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if ((jsonObj.get("deleted_at") != null && !jsonObj.get("deleted_at").isJsonNull()) && !jsonObj.get("deleted_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `deleted_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deleted_at").toString()));
      }
      if ((jsonObj.get("digi_ident") != null && !jsonObj.get("digi_ident").isJsonNull()) && !jsonObj.get("digi_ident").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `digi_ident` to be a primitive type in the JSON string but got `%s`", jsonObj.get("digi_ident").toString()));
      }
      if ((jsonObj.get("dl_ident") != null && !jsonObj.get("dl_ident").isJsonNull()) && !jsonObj.get("dl_ident").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dl_ident` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dl_ident").toString()));
      }
      if ((jsonObj.get("pp_ident") != null && !jsonObj.get("pp_ident").isJsonNull()) && !jsonObj.get("pp_ident").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pp_ident` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pp_ident").toString()));
      }
      if (jsonObj.get("training") != null && !jsonObj.get("training").isJsonNull()) {
        JsonArray jsonArraytraining = jsonObj.getAsJsonArray("training");
        if (jsonArraytraining != null) {
          // ensure the json data is an array
          if (!jsonObj.get("training").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `training` to be an array in the JSON string but got `%s`", jsonObj.get("training").toString()));
          }

          // validate the optional field `training` (array)
          for (int i = 0; i < jsonArraytraining.size(); i++) {
            Training.validateJsonElement(jsonArraytraining.get(i));
          };
        }
      }
      if (jsonObj.get("history") != null && !jsonObj.get("history").isJsonNull()) {
        JsonArray jsonArrayhistory = jsonObj.getAsJsonArray("history");
        if (jsonArrayhistory != null) {
          // ensure the json data is an array
          if (!jsonObj.get("history").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `history` to be an array in the JSON string but got `%s`", jsonObj.get("history").toString()));
          }

          // validate the optional field `history` (array)
          for (int i = 0; i < jsonArrayhistory.size(); i++) {
            QueryQuery200ResponseDataRegistryAllOfHistoryInner.validateJsonElement(jsonArrayhistory.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QueryQuery200ResponseDataRegistry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QueryQuery200ResponseDataRegistry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QueryQuery200ResponseDataRegistry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QueryQuery200ResponseDataRegistry.class));

       return (TypeAdapter<T>) new TypeAdapter<QueryQuery200ResponseDataRegistry>() {
           @Override
           public void write(JsonWriter out, QueryQuery200ResponseDataRegistry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QueryQuery200ResponseDataRegistry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QueryQuery200ResponseDataRegistry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QueryQuery200ResponseDataRegistry
   * @throws IOException if the JSON string is invalid with respect to QueryQuery200ResponseDataRegistry
   */
  public static QueryQuery200ResponseDataRegistry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QueryQuery200ResponseDataRegistry.class);
  }

  /**
   * Convert an instance of QueryQuery200ResponseDataRegistry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

