/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import uk.ac.hdruk.safepeopleregistryapi.JSON;

/**
 * Training model
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-18T08:34:20.150560795Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class Training {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private String updatedAt;

  public static final String SERIALIZED_NAME_REGISTRY_ID = "registry_id";
  @SerializedName(SERIALIZED_NAME_REGISTRY_ID)
  @javax.annotation.Nullable
  private Integer registryId;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private String provider;

  public static final String SERIALIZED_NAME_AWARDED_AT = "awarded_at";
  @SerializedName(SERIALIZED_NAME_AWARDED_AT)
  @javax.annotation.Nullable
  private String awardedAt;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private String expiresAt;

  public static final String SERIALIZED_NAME_EXPIRES_IN_YEARS = "expires_in_years";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN_YEARS)
  @javax.annotation.Nullable
  private Integer expiresInYears;

  public static final String SERIALIZED_NAME_TRAINING_NAME = "training_name";
  @SerializedName(SERIALIZED_NAME_TRAINING_NAME)
  @javax.annotation.Nullable
  private String trainingName;

  public static final String SERIALIZED_NAME_PRO_REGISTRATION = "pro_registration";
  @SerializedName(SERIALIZED_NAME_PRO_REGISTRATION)
  @javax.annotation.Nullable
  private Integer proRegistration;

  public Training() {
  }

  public Training id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Training createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public Training updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Training registryId(@javax.annotation.Nullable Integer registryId) {
    this.registryId = registryId;
    return this;
  }

  /**
   * Get registryId
   * @return registryId
   */
  @javax.annotation.Nullable
  public Integer getRegistryId() {
    return registryId;
  }

  public void setRegistryId(@javax.annotation.Nullable Integer registryId) {
    this.registryId = registryId;
  }


  public Training provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public String getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public Training awardedAt(@javax.annotation.Nullable String awardedAt) {
    this.awardedAt = awardedAt;
    return this;
  }

  /**
   * Get awardedAt
   * @return awardedAt
   */
  @javax.annotation.Nullable
  public String getAwardedAt() {
    return awardedAt;
  }

  public void setAwardedAt(@javax.annotation.Nullable String awardedAt) {
    this.awardedAt = awardedAt;
  }


  public Training expiresAt(@javax.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public String getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable String expiresAt) {
    this.expiresAt = expiresAt;
  }


  public Training expiresInYears(@javax.annotation.Nullable Integer expiresInYears) {
    this.expiresInYears = expiresInYears;
    return this;
  }

  /**
   * Get expiresInYears
   * @return expiresInYears
   */
  @javax.annotation.Nullable
  public Integer getExpiresInYears() {
    return expiresInYears;
  }

  public void setExpiresInYears(@javax.annotation.Nullable Integer expiresInYears) {
    this.expiresInYears = expiresInYears;
  }


  public Training trainingName(@javax.annotation.Nullable String trainingName) {
    this.trainingName = trainingName;
    return this;
  }

  /**
   * Get trainingName
   * @return trainingName
   */
  @javax.annotation.Nullable
  public String getTrainingName() {
    return trainingName;
  }

  public void setTrainingName(@javax.annotation.Nullable String trainingName) {
    this.trainingName = trainingName;
  }


  public Training proRegistration(@javax.annotation.Nullable Integer proRegistration) {
    this.proRegistration = proRegistration;
    return this;
  }

  /**
   * Get proRegistration
   * @return proRegistration
   */
  @javax.annotation.Nullable
  public Integer getProRegistration() {
    return proRegistration;
  }

  public void setProRegistration(@javax.annotation.Nullable Integer proRegistration) {
    this.proRegistration = proRegistration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Training training = (Training) o;
    return Objects.equals(this.id, training.id) &&
        Objects.equals(this.createdAt, training.createdAt) &&
        Objects.equals(this.updatedAt, training.updatedAt) &&
        Objects.equals(this.registryId, training.registryId) &&
        Objects.equals(this.provider, training.provider) &&
        Objects.equals(this.awardedAt, training.awardedAt) &&
        Objects.equals(this.expiresAt, training.expiresAt) &&
        Objects.equals(this.expiresInYears, training.expiresInYears) &&
        Objects.equals(this.trainingName, training.trainingName) &&
        Objects.equals(this.proRegistration, training.proRegistration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, updatedAt, registryId, provider, awardedAt, expiresAt, expiresInYears, trainingName, proRegistration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Training {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    registryId: ").append(toIndentedString(registryId)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    awardedAt: ").append(toIndentedString(awardedAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    expiresInYears: ").append(toIndentedString(expiresInYears)).append("\n");
    sb.append("    trainingName: ").append(toIndentedString(trainingName)).append("\n");
    sb.append("    proRegistration: ").append(toIndentedString(proRegistration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "created_at", "updated_at", "registry_id", "provider", "awarded_at", "expires_at", "expires_in_years", "training_name", "pro_registration"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Training
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Training.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Training is not found in the empty JSON string", Training.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Training.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Training` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("updated_at") != null && !jsonObj.get("updated_at").isJsonNull()) && !jsonObj.get("updated_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `updated_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updated_at").toString()));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("awarded_at") != null && !jsonObj.get("awarded_at").isJsonNull()) && !jsonObj.get("awarded_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `awarded_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("awarded_at").toString()));
      }
      if ((jsonObj.get("expires_at") != null && !jsonObj.get("expires_at").isJsonNull()) && !jsonObj.get("expires_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expires_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expires_at").toString()));
      }
      if ((jsonObj.get("training_name") != null && !jsonObj.get("training_name").isJsonNull()) && !jsonObj.get("training_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `training_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("training_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Training.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Training' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Training> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Training.class));

       return (TypeAdapter<T>) new TypeAdapter<Training>() {
           @Override
           public void write(JsonWriter out, Training value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Training read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Training given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Training
   * @throws IOException if the JSON string is invalid with respect to Training
   */
  public static Training fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Training.class);
  }

  /**
   * Convert an instance of Training to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

