/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.api;

import uk.ac.hdruk.safepeopleregistryapi.ApiException;
import uk.ac.hdruk.safepeopleregistryapi.model.AccreditationIndexByRegistryId400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.CustodianProjectOrganisationsShow404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ProjectHasOrganisation;
import uk.ac.hdruk.safepeopleregistryapi.model.ProjectHasOrganisationShow500Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectHasOrganisationApi
 */
@Disabled
public class ProjectHasOrganisationApiTest {

    private final ProjectHasOrganisationApi api = new ProjectHasOrganisationApi();

    /**
     * Get details of a project-organisation relationship
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void projectHasOrganisationShowTest() throws ApiException {
        Integer projectOrganisationId = null;
        ProjectHasOrganisation response = api.projectHasOrganisationShow(projectOrganisationId);
        // TODO: test validations
    }

}
