/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.api;

import uk.ac.hdruk.safepeopleregistryapi.ApiException;
import uk.ac.hdruk.safepeopleregistryapi.model.AccreditationIndexByRegistryId400Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationCheck;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationChecksDestroy200Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationChecksShow404Response;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationChecksStoreRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ValidationChecksApi
 */
@Disabled
public class ValidationChecksApiTest {

    private final ValidationChecksApi api = new ValidationChecksApi();

    /**
     * Delete a validation check
     *
     * Remove a validation check.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validationChecksDestroyTest() throws ApiException {
        Integer id = null;
        ValidationChecksDestroy200Response response = api.validationChecksDestroy(id);
        // TODO: test validations
    }

    /**
     * List all validation checks
     *
     * Retrieve all validation checks.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validationChecksIndexTest() throws ApiException {
        List<ValidationCheck> response = api.validationChecksIndex();
        // TODO: test validations
    }

    /**
     * Get a single validation check
     *
     * Retrieve a specific validation check by ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validationChecksShowTest() throws ApiException {
        Integer id = null;
        ValidationCheck response = api.validationChecksShow(id);
        // TODO: test validations
    }

    /**
     * Create a new validation check
     *
     * Create a new validation check entry.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validationChecksStoreTest() throws ApiException {
        ValidationChecksStoreRequest validationChecksStoreRequest = null;
        ValidationCheck response = api.validationChecksStore(validationChecksStoreRequest);
        // TODO: test validations
    }

    /**
     * Update a validation check
     *
     * Edit an existing validation check.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validationChecksUpdateTest() throws ApiException {
        Integer id = null;
        ValidationChecksStoreRequest validationChecksStoreRequest = null;
        ValidationCheck response = api.validationChecksUpdate(id, validationChecksStoreRequest);
        // TODO: test validations
    }

}
