/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustodianGetProjectsUsers200ResponseDataDataInnerProject
 */
public class CustodianGetProjectsUsers200ResponseDataDataInnerProjectTest {
    private final CustodianGetProjectsUsers200ResponseDataDataInnerProject model = new CustodianGetProjectsUsers200ResponseDataDataInnerProject();

    /**
     * Model tests for CustodianGetProjectsUsers200ResponseDataDataInnerProject
     */
    @Test
    public void testCustodianGetProjectsUsers200ResponseDataDataInnerProject() {
        // TODO: test CustodianGetProjectsUsers200ResponseDataDataInnerProject
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

}
