/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Custodian
 */
public class CustodianTest {
    private final Custodian model = new Custodian();

    /**
     * Model tests for Custodian
     */
    @Test
    public void testCustodian() {
        // TODO: test Custodian
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'uniqueIdentifier'
     */
    @Test
    public void uniqueIdentifierTest() {
        // TODO: test uniqueIdentifier
    }

    /**
     * Test the property 'contactEmail'
     */
    @Test
    public void contactEmailTest() {
        // TODO: test contactEmail
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'inviteAcceptedAt'
     */
    @Test
    public void inviteAcceptedAtTest() {
        // TODO: test inviteAcceptedAt
    }

    /**
     * Test the property 'inviteSentAt'
     */
    @Test
    public void inviteSentAtTest() {
        // TODO: test inviteSentAt
    }

    /**
     * Test the property 'idvtRequired'
     */
    @Test
    public void idvtRequiredTest() {
        // TODO: test idvtRequired
    }

    /**
     * Test the property 'gatewayAppId'
     */
    @Test
    public void gatewayAppIdTest() {
        // TODO: test gatewayAppId
    }

    /**
     * Test the property 'gatewayClientId'
     */
    @Test
    public void gatewayClientIdTest() {
        // TODO: test gatewayClientId
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

}
