/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import uk.ac.hdruk.safepeopleregistryapi.model.NotificationsGetNotificationCounts200ResponseData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotificationsGetNotificationCounts200Response
 */
public class NotificationsGetNotificationCounts200ResponseTest {
    private final NotificationsGetNotificationCounts200Response model = new NotificationsGetNotificationCounts200Response();

    /**
     * Model tests for NotificationsGetNotificationCounts200Response
     */
    @Test
    public void testNotificationsGetNotificationCounts200Response() {
        // TODO: test NotificationsGetNotificationCounts200Response
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
