/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotificationsGetNotificationCounts200ResponseData
 */
public class NotificationsGetNotificationCounts200ResponseDataTest {
    private final NotificationsGetNotificationCounts200ResponseData model = new NotificationsGetNotificationCounts200ResponseData();

    /**
     * Model tests for NotificationsGetNotificationCounts200ResponseData
     */
    @Test
    public void testNotificationsGetNotificationCounts200ResponseData() {
        // TODO: test NotificationsGetNotificationCounts200ResponseData
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'read'
     */
    @Test
    public void readTest() {
        // TODO: test read
    }

    /**
     * Test the property 'unread'
     */
    @Test
    public void unreadTest() {
        // TODO: test unread
    }

}
