/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner
 */
public class ProjectGetAllUsersFlagProjectByUserId200ResponseDataInnerTest {
    private final ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner model = new ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner();

    /**
     * Model tests for ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner
     */
    @Test
    public void testProjectGetAllUsersFlagProjectByUserId200ResponseDataInner() {
        // TODO: test ProjectGetAllUsersFlagProjectByUserId200ResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'projectUserId'
     */
    @Test
    public void projectUserIdTest() {
        // TODO: test projectUserId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'registryId'
     */
    @Test
    public void registryIdTest() {
        // TODO: test registryId
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'professionalEmail'
     */
    @Test
    public void professionalEmailTest() {
        // TODO: test professionalEmail
    }

    /**
     * Test the property 'affiliationId'
     */
    @Test
    public void affiliationIdTest() {
        // TODO: test affiliationId
    }

    /**
     * Test the property 'organisationName'
     */
    @Test
    public void organisationNameTest() {
        // TODO: test organisationName
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
