/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import uk.ac.hdruk.safepeopleregistryapi.model.ProjectUpdateAllProjectUsersRequestUsersInnerRole;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectUpdateAllProjectUsersRequestUsersInner
 */
public class ProjectUpdateAllProjectUsersRequestUsersInnerTest {
    private final ProjectUpdateAllProjectUsersRequestUsersInner model = new ProjectUpdateAllProjectUsersRequestUsersInner();

    /**
     * Model tests for ProjectUpdateAllProjectUsersRequestUsersInner
     */
    @Test
    public void testProjectUpdateAllProjectUsersRequestUsersInner() {
        // TODO: test ProjectUpdateAllProjectUsersRequestUsersInner
    }

    /**
     * Test the property 'registryId'
     */
    @Test
    public void registryIdTest() {
        // TODO: test registryId
    }

    /**
     * Test the property 'affiliationId'
     */
    @Test
    public void affiliationIdTest() {
        // TODO: test affiliationId
    }

    /**
     * Test the property 'projectUserId'
     */
    @Test
    public void projectUserIdTest() {
        // TODO: test projectUserId
    }

    /**
     * Test the property 'primaryContact'
     */
    @Test
    public void primaryContactTest() {
        // TODO: test primaryContact
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
