/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectMakePrimaryContactRequest
 */
public class ProjectMakePrimaryContactRequestTest {
    private final ProjectMakePrimaryContactRequest model = new ProjectMakePrimaryContactRequest();

    /**
     * Model tests for ProjectMakePrimaryContactRequest
     */
    @Test
    public void testProjectMakePrimaryContactRequest() {
        // TODO: test ProjectMakePrimaryContactRequest
    }

    /**
     * Test the property 'primaryContact'
     */
    @Test
    public void primaryContactTest() {
        // TODO: test primaryContact
    }

}
