/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import uk.ac.hdruk.safepeopleregistryapi.model.Affiliation;
import uk.ac.hdruk.safepeopleregistryapi.model.Project;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryQuery200ResponseDataRegistryAllOfHistoryInner
 */
public class QueryQuery200ResponseDataRegistryAllOfHistoryInnerTest {
    private final QueryQuery200ResponseDataRegistryAllOfHistoryInner model = new QueryQuery200ResponseDataRegistryAllOfHistoryInner();

    /**
     * Model tests for QueryQuery200ResponseDataRegistryAllOfHistoryInner
     */
    @Test
    public void testQueryQuery200ResponseDataRegistryAllOfHistoryInner() {
        // TODO: test QueryQuery200ResponseDataRegistryAllOfHistoryInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'affiliationId'
     */
    @Test
    public void affiliationIdTest() {
        // TODO: test affiliationId
    }

    /**
     * Test the property 'endorsementId'
     */
    @Test
    public void endorsementIdTest() {
        // TODO: test endorsementId
    }

    /**
     * Test the property 'infringementId'
     */
    @Test
    public void infringementIdTest() {
        // TODO: test infringementId
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'accessKeyId'
     */
    @Test
    public void accessKeyIdTest() {
        // TODO: test accessKeyId
    }

    /**
     * Test the property 'custodianIdentifier'
     */
    @Test
    public void custodianIdentifierTest() {
        // TODO: test custodianIdentifier
    }

    /**
     * Test the property 'ledgerHash'
     */
    @Test
    public void ledgerHashTest() {
        // TODO: test ledgerHash
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'affiliation'
     */
    @Test
    public void affiliationTest() {
        // TODO: test affiliation
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

}
