/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RegistryHasAffiliation
 */
public class RegistryHasAffiliationTest {
    private final RegistryHasAffiliation model = new RegistryHasAffiliation();

    /**
     * Model tests for RegistryHasAffiliation
     */
    @Test
    public void testRegistryHasAffiliation() {
        // TODO: test RegistryHasAffiliation
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'registryId'
     */
    @Test
    public void registryIdTest() {
        // TODO: test registryId
    }

    /**
     * Test the property 'affiliationId'
     */
    @Test
    public void affiliationIdTest() {
        // TODO: test affiliationId
    }

}
