/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SsoTenant
 */
public class SsoTenantTest {
    private final SsoTenant model = new SsoTenant();

    /**
     * Model tests for SsoTenant
     */
    @Test
    public void testSsoTenant() {
        // TODO: test SsoTenant
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'idpAlias'
     */
    @Test
    public void idpAliasTest() {
        // TODO: test idpAlias
    }

    /**
     * Test the property 'metadataUrl'
     */
    @Test
    public void metadataUrlTest() {
        // TODO: test metadataUrl
    }

    /**
     * Test the property 'entityId'
     */
    @Test
    public void entityIdTest() {
        // TODO: test entityId
    }

    /**
     * Test the property 'metadataImportedAt'
     */
    @Test
    public void metadataImportedAtTest() {
        // TODO: test metadataImportedAt
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'spEntityId'
     */
    @Test
    public void spEntityIdTest() {
        // TODO: test spEntityId
    }

    /**
     * Test the property 'spAcsUrl'
     */
    @Test
    public void spAcsUrlTest() {
        // TODO: test spAcsUrl
    }

    /**
     * Test the property 'spMetadataUrl'
     */
    @Test
    public void spMetadataUrlTest() {
        // TODO: test spMetadataUrl
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'submittedByUserId'
     */
    @Test
    public void submittedByUserIdTest() {
        // TODO: test submittedByUserId
    }

    /**
     * Test the property 'rejectedReason'
     */
    @Test
    public void rejectedReasonTest() {
        // TODO: test rejectedReason
    }

}
