/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import uk.ac.hdruk.safepeopleregistryapi.model.ValidationLog;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValidationLogsGetCustodianProjectUserValidationLogs200Response
 */
public class ValidationLogsGetCustodianProjectUserValidationLogs200ResponseTest {
    private final ValidationLogsGetCustodianProjectUserValidationLogs200Response model = new ValidationLogsGetCustodianProjectUserValidationLogs200Response();

    /**
     * Model tests for ValidationLogsGetCustodianProjectUserValidationLogs200Response
     */
    @Test
    public void testValidationLogsGetCustodianProjectUserValidationLogs200Response() {
        // TODO: test ValidationLogsGetCustodianProjectUserValidationLogs200Response
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
