/*
 * Safe People Registry API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.ac.hdruk.safepeopleregistryapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhooksCreateReceiverRequest
 */
public class WebhooksCreateReceiverRequestTest {
    private final WebhooksCreateReceiverRequest model = new WebhooksCreateReceiverRequest();

    /**
     * Model tests for WebhooksCreateReceiverRequest
     */
    @Test
    public void testWebhooksCreateReceiverRequest() {
        // TODO: test WebhooksCreateReceiverRequest
    }

    /**
     * Test the property 'custodianId'
     */
    @Test
    public void custodianIdTest() {
        // TODO: test custodianId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'webhookEventId'
     */
    @Test
    public void webhookEventIdTest() {
        // TODO: test webhookEventId
    }

}
